#!/usr/bin/env bash
# Build the host-side Glide wrapper (libglide2x) into build/glide.
#
# qemu-3dfx's Glide pass-through (hw/3dfx) is only a dispatcher: at
# grGlideInit it dlopens libglide2x and looks up the 183 gr*/gu* entry
# points in it. Upstream ships that library to donors only, so we build our
# own from OpenGLide (LGPL, third_party/openglide) with the window-less
# platform layer in glidept/host/ — doc 12 §5, patches/openglide/README.md.
#
#   scripts/build-glide.sh            this host
#
# The result is loaded by QEMU, not linked into it: point it at the build
# with QEMU_GLIDE_LIB=build/glide/libglide2x.so (patch 33), or install it
# next to libqemu-embed.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OG="$ROOT/third_party/openglide"

[ -f "$OG/Glide.cpp" ] || { echo "openglide submodule missing (git submodule update --init third_party/openglide)"; exit 1; }

OUT="$ROOT/build/glide"; mkdir -p "$OUT"
# platform/linux is the platform layer on both hosts: what we take from it
# (clock.cpp, library.cpp) is POSIX, and __unix__ is what sdk2_3dfx.h looks
# for. macOS has no GL/ headers -- the framework keeps its own under
# OpenGL/, and the only GL/ on the box is XQuartz's Mesa, the one
# implementation this must not bind to -- so glidept/host/macos puts a
# forwarding <GL/gl.h> and <GL/glext.h> on the include path there, and only
# there.
INC=()
if [ "$(uname -s)" = Darwin ]; then
  LIB="$OUT/libglide2x.dylib"; SHARED=(-dynamiclib -install_name "$LIB")
  GL=(-framework OpenGL); PLATDIR="$OG/platform/linux"; OSDEF=(-D__unix__ -D__linux__)
  INC=(-I"$ROOT/glidept/host/macos")
else
  LIB="$OUT/libglide2x.so"; SHARED=(-shared)
  GL=(-lGL); PLATDIR="$OG/platform/linux"; OSDEF=(-D__unix__ -D__linux__)
fi
CXX="${CXX:-c++}"

# OpenGLide is an autotools project; we compile its sources directly rather
# than carry its configure (SDL 1.2, X11 and GLU are all things this build
# exists to do without). config.h is the handful of defines its sources
# actually read. HAVE_MMX is deliberately *not* defined: it selects inline
# x86 MMX in FormatConversion.cpp, and the portable C paths beside it are
# what an Apple Silicon host needs anyway.
cat > "$OUT/config.h" <<EOF
/* generated by scripts/build-glide.sh — do not edit */
#define SIZEOF_INT_P $(getconf LONG_BIT 2>/dev/null | awk '{print $1/8}')
#define PACKAGE_VERSION "openglide-$(git -C "$OG" rev-parse --short HEAD 2>/dev/null || echo unknown)"
EOF

srcs=()
for f in "$OG"/*.cpp; do
  # gbanner is the splash-image generator tool, not part of the library
  [ "$(basename "$f")" = gbanner.cpp ] && continue
  srcs+=("$f")
done
# clock.cpp and library.cpp come from OpenGLide's own Unix platform; window,
# openglext and error are ours (glidept/host), and so are the entry points
# hw/3dfx looks for and the two GLU calls we replaced.
srcs+=("$PLATDIR/clock.cpp" "$PLATDIR/library.cpp")
srcs+=("$ROOT"/glidept/host/*.cpp)

echo "==> ${#srcs[@]} sources -> $LIB"
"$CXX" -std=c++17 -O2 -fPIC -w -DHAVE_CONFIG_H "${OSDEF[@]}" "${SHARED[@]}" -o "$LIB" \
  "${srcs[@]}" \
  -I"$OUT" -I"$OG" -I"$PLATDIR" -I"$ROOT/glidept" -I"$ROOT/glidept/host" "${INC[@]}" \
  "${GL[@]}" -ldl
echo "==> $LIB"
