/* generated by gen_vtbl8.py from mingw d3d8.h; do not edit */
#ifndef D3D8_VTBL_H
#define D3D8_VTBL_H
typedef struct IDirect3D8 IDirect3D8;
typedef struct IDirect3DDevice8 IDirect3DDevice8;
typedef struct IDirect3DSurface8 IDirect3DSurface8;
typedef struct IDirect3DTexture8 IDirect3DTexture8;
typedef struct IDirect3DCubeTexture8 IDirect3DCubeTexture8;
typedef struct IDirect3DVertexBuffer8 IDirect3DVertexBuffer8;
typedef struct IDirect3DIndexBuffer8 IDirect3DIndexBuffer8;
typedef struct IDirect3DSwapChain8 IDirect3DSwapChain8;
typedef struct IDirect3DVolumeTexture8 IDirect3DVolumeTexture8;
typedef struct IDirect3DVolume8 IDirect3DVolume8;
typedef struct IDirect3DBaseTexture8 IDirect3DBaseTexture8;
typedef struct IDirect3D8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3D8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3D8 *This);
    ULONG (WINAPI *Release)(IDirect3D8 *This);
    HRESULT (WINAPI *RegisterSoftwareDevice)(IDirect3D8 *This, void * pInitializeFunction);
    UINT (WINAPI *GetAdapterCount)(IDirect3D8 *This);
    HRESULT (WINAPI *GetAdapterIdentifier)(IDirect3D8 *This, UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER8 * pIdentifier);
    UINT (WINAPI *GetAdapterModeCount)(IDirect3D8 *This, UINT Adapter);
    HRESULT (WINAPI *EnumAdapterModes)(IDirect3D8 *This, UINT Adapter, UINT Mode, D3DDISPLAYMODE * pMode);
    HRESULT (WINAPI *GetAdapterDisplayMode)(IDirect3D8 *This, UINT Adapter, D3DDISPLAYMODE * pMode);
    HRESULT (WINAPI *CheckDeviceType)(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE CheckType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, WINBOOL Windowed);
    HRESULT (WINAPI *CheckDeviceFormat)(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat);
    HRESULT (WINAPI *CheckDeviceMultiSampleType)(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, WINBOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType);
    HRESULT (WINAPI *CheckDepthStencilMatch)(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat);
    HRESULT (WINAPI *GetDeviceCaps)(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS8 * pCaps);
    HMONITOR (WINAPI *GetAdapterMonitor)(IDirect3D8 *This, UINT Adapter);
    HRESULT (WINAPI *CreateDevice)(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType,HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS8 * pPresentationParameters, IDirect3DDevice8 ** ppReturnedDeviceInterface);
} IDirect3D8Vtbl;
struct IDirect3D8 { const IDirect3D8Vtbl *lpVtbl; };
/* --- IDirect3D8: 16 methods --- */
HRESULT WINAPI d8_QueryInterface(IDirect3D8 *This, REFIID riid, void** ppvObject);
ULONG WINAPI d8_AddRef(IDirect3D8 *This);
ULONG WINAPI d8_Release(IDirect3D8 *This);
HRESULT WINAPI d8_RegisterSoftwareDevice(IDirect3D8 *This, void * pInitializeFunction);
UINT WINAPI d8_GetAdapterCount(IDirect3D8 *This);
HRESULT WINAPI d8_GetAdapterIdentifier(IDirect3D8 *This, UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER8 * pIdentifier);
UINT WINAPI d8_GetAdapterModeCount(IDirect3D8 *This, UINT Adapter);
HRESULT WINAPI d8_EnumAdapterModes(IDirect3D8 *This, UINT Adapter, UINT Mode, D3DDISPLAYMODE * pMode);
HRESULT WINAPI d8_GetAdapterDisplayMode(IDirect3D8 *This, UINT Adapter, D3DDISPLAYMODE * pMode);
HRESULT WINAPI d8_CheckDeviceType(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE CheckType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, WINBOOL Windowed);
HRESULT WINAPI d8_CheckDeviceFormat(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat);
HRESULT WINAPI d8_CheckDeviceMultiSampleType(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, WINBOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType);
HRESULT WINAPI d8_CheckDepthStencilMatch(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat);
HRESULT WINAPI d8_GetDeviceCaps(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS8 * pCaps);
HMONITOR WINAPI d8_GetAdapterMonitor(IDirect3D8 *This, UINT Adapter);
HRESULT WINAPI d8_CreateDevice(IDirect3D8 *This, UINT Adapter, D3DDEVTYPE DeviceType,HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS8 * pPresentationParameters, IDirect3DDevice8 ** ppReturnedDeviceInterface);
static const IDirect3D8Vtbl d8_vtbl = {
    d8_QueryInterface,
    d8_AddRef,
    d8_Release,
    d8_RegisterSoftwareDevice,
    d8_GetAdapterCount,
    d8_GetAdapterIdentifier,
    d8_GetAdapterModeCount,
    d8_EnumAdapterModes,
    d8_GetAdapterDisplayMode,
    d8_CheckDeviceType,
    d8_CheckDeviceFormat,
    d8_CheckDeviceMultiSampleType,
    d8_CheckDepthStencilMatch,
    d8_GetDeviceCaps,
    d8_GetAdapterMonitor,
    d8_CreateDevice,
};

typedef struct IDirect3DDevice8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DDevice8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DDevice8 *This);
    ULONG (WINAPI *Release)(IDirect3DDevice8 *This);
    HRESULT (WINAPI *TestCooperativeLevel)(IDirect3DDevice8 *This);
    UINT (WINAPI *GetAvailableTextureMem)(IDirect3DDevice8 *This);
    HRESULT (WINAPI *ResourceManagerDiscardBytes)(IDirect3DDevice8 *This, DWORD Bytes);
    HRESULT (WINAPI *GetDirect3D)(IDirect3DDevice8 *This, IDirect3D8 ** ppD3D8);
    HRESULT (WINAPI *GetDeviceCaps)(IDirect3DDevice8 *This, D3DCAPS8 * pCaps);
    HRESULT (WINAPI *GetDisplayMode)(IDirect3DDevice8 *This, D3DDISPLAYMODE * pMode);
    HRESULT (WINAPI *GetCreationParameters)(IDirect3DDevice8 *This, D3DDEVICE_CREATION_PARAMETERS * pParameters);
    HRESULT (WINAPI *SetCursorProperties)(IDirect3DDevice8 *This, UINT XHotSpot, UINT YHotSpot, IDirect3DSurface8 * pCursorBitmap);
    void (WINAPI *SetCursorPosition)(IDirect3DDevice8 *This, UINT XScreenSpace, UINT YScreenSpace,DWORD Flags);
    WINBOOL (WINAPI *ShowCursor)(IDirect3DDevice8 *This, WINBOOL bShow);
    HRESULT (WINAPI *CreateAdditionalSwapChain)(IDirect3DDevice8 *This, D3DPRESENT_PARAMETERS8 * pPresentationParameters, IDirect3DSwapChain8 ** pSwapChain);
    HRESULT (WINAPI *Reset)(IDirect3DDevice8 *This, D3DPRESENT_PARAMETERS8 * pPresentationParameters);
    HRESULT (WINAPI *Present)(IDirect3DDevice8 *This, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region);
    HRESULT (WINAPI *GetBackBuffer)(IDirect3DDevice8 *This, UINT BackBuffer,D3DBACKBUFFER_TYPE Type,IDirect3DSurface8 ** ppBackBuffer);
    HRESULT (WINAPI *GetRasterStatus)(IDirect3DDevice8 *This, D3DRASTER_STATUS * pRasterStatus);
    void (WINAPI *SetGammaRamp)(IDirect3DDevice8 *This, DWORD flags, const D3DGAMMARAMP *ramp);
    void (WINAPI *GetGammaRamp)(IDirect3DDevice8 *This, D3DGAMMARAMP * pRamp);
    HRESULT (WINAPI *CreateTexture)(IDirect3DDevice8 *This, UINT Width,UINT Height,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DTexture8 ** ppTexture);
    HRESULT (WINAPI *CreateVolumeTexture)(IDirect3DDevice8 *This, UINT Width,UINT Height,UINT Depth,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DVolumeTexture8 ** ppVolumeTexture);
    HRESULT (WINAPI *CreateCubeTexture)(IDirect3DDevice8 *This, UINT EdgeLength,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DCubeTexture8 ** ppCubeTexture);
    HRESULT (WINAPI *CreateVertexBuffer)(IDirect3DDevice8 *This, UINT Length,DWORD Usage,DWORD FVF,D3DPOOL Pool,IDirect3DVertexBuffer8 ** ppVertexBuffer);
    HRESULT (WINAPI *CreateIndexBuffer)(IDirect3DDevice8 *This, UINT Length,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DIndexBuffer8 ** ppIndexBuffer);
    HRESULT (WINAPI *CreateRenderTarget)(IDirect3DDevice8 *This, UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,WINBOOL Lockable,IDirect3DSurface8 ** ppSurface);
    HRESULT (WINAPI *CreateDepthStencilSurface)(IDirect3DDevice8 *This, UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,IDirect3DSurface8 ** ppSurface);
    HRESULT (WINAPI *CreateImageSurface)(IDirect3DDevice8 *This, UINT Width,UINT Height,D3DFORMAT Format,IDirect3DSurface8 ** ppSurface);
    HRESULT (WINAPI *CopyRects)(IDirect3DDevice8 *This, IDirect3DSurface8 *src_surface, const RECT *src_rects, UINT rect_count, IDirect3DSurface8 *dst_surface, const POINT *dst_points);
    HRESULT (WINAPI *UpdateTexture)(IDirect3DDevice8 *This, IDirect3DBaseTexture8 * pSourceTexture,IDirect3DBaseTexture8 * pDestinationTexture);
    HRESULT (WINAPI *GetFrontBuffer)(IDirect3DDevice8 *This, IDirect3DSurface8 * pDestSurface);
    HRESULT (WINAPI *SetRenderTarget)(IDirect3DDevice8 *This, IDirect3DSurface8 * pRenderTarget,IDirect3DSurface8 * pNewZStencil);
    HRESULT (WINAPI *GetRenderTarget)(IDirect3DDevice8 *This, IDirect3DSurface8 ** ppRenderTarget);
    HRESULT (WINAPI *GetDepthStencilSurface)(IDirect3DDevice8 *This, IDirect3DSurface8 ** ppZStencilSurface);
    HRESULT (WINAPI *BeginScene)(IDirect3DDevice8 *This);
    HRESULT (WINAPI *EndScene)(IDirect3DDevice8 *This);
    HRESULT (WINAPI *Clear)(IDirect3DDevice8 *This, DWORD rect_count, const D3DRECT *rects, DWORD flags, D3DCOLOR color, float z, DWORD stencil);
    HRESULT (WINAPI *SetTransform)(IDirect3DDevice8 *This, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix);
    HRESULT (WINAPI *GetTransform)(IDirect3DDevice8 *This, D3DTRANSFORMSTATETYPE State,D3DMATRIX * pMatrix);
    HRESULT (WINAPI *MultiplyTransform)(IDirect3DDevice8 *This, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix);
    HRESULT (WINAPI *SetViewport)(IDirect3DDevice8 *This, const D3DVIEWPORT9 *viewport);
    HRESULT (WINAPI *GetViewport)(IDirect3DDevice8 *This, D3DVIEWPORT9 * pViewport);
    HRESULT (WINAPI *SetMaterial)(IDirect3DDevice8 *This, const D3DMATERIAL9 *material);
    HRESULT (WINAPI *GetMaterial)(IDirect3DDevice8 *This, D3DMATERIAL9 *pMaterial);
    HRESULT (WINAPI *SetLight)(IDirect3DDevice8 *This, DWORD index, const D3DLIGHT9 *light);
    HRESULT (WINAPI *GetLight)(IDirect3DDevice8 *This, DWORD Index,D3DLIGHT9 * pLight);
    HRESULT (WINAPI *LightEnable)(IDirect3DDevice8 *This, DWORD Index,WINBOOL Enable);
    HRESULT (WINAPI *GetLightEnable)(IDirect3DDevice8 *This, DWORD Index,WINBOOL * pEnable);
    HRESULT (WINAPI *SetClipPlane)(IDirect3DDevice8 *This, DWORD index, const float *plane);
    HRESULT (WINAPI *GetClipPlane)(IDirect3DDevice8 *This, DWORD Index,float * pPlane);
    HRESULT (WINAPI *SetRenderState)(IDirect3DDevice8 *This, D3DRENDERSTATETYPE State,DWORD Value);
    HRESULT (WINAPI *GetRenderState)(IDirect3DDevice8 *This, D3DRENDERSTATETYPE State,DWORD * pValue);
    HRESULT (WINAPI *BeginStateBlock)(IDirect3DDevice8 *This);
    HRESULT (WINAPI *EndStateBlock)(IDirect3DDevice8 *This, DWORD * pToken);
    HRESULT (WINAPI *ApplyStateBlock)(IDirect3DDevice8 *This, DWORD Token);
    HRESULT (WINAPI *CaptureStateBlock)(IDirect3DDevice8 *This, DWORD Token);
    HRESULT (WINAPI *DeleteStateBlock)(IDirect3DDevice8 *This, DWORD Token);
    HRESULT (WINAPI *CreateStateBlock)(IDirect3DDevice8 *This, D3DSTATEBLOCKTYPE Type,DWORD * pToken);
    HRESULT (WINAPI *SetClipStatus)(IDirect3DDevice8 *This, const D3DCLIPSTATUS8 *clip_status);
    HRESULT (WINAPI *GetClipStatus)(IDirect3DDevice8 *This, D3DCLIPSTATUS8 * pClipStatus);
    HRESULT (WINAPI *GetTexture)(IDirect3DDevice8 *This, DWORD Stage,IDirect3DBaseTexture8 ** ppTexture);
    HRESULT (WINAPI *SetTexture)(IDirect3DDevice8 *This, DWORD Stage,IDirect3DBaseTexture8 * pTexture);
    HRESULT (WINAPI *GetTextureStageState)(IDirect3DDevice8 *This, DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD * pValue);
    HRESULT (WINAPI *SetTextureStageState)(IDirect3DDevice8 *This, DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD Value);
    HRESULT (WINAPI *ValidateDevice)(IDirect3DDevice8 *This, DWORD * pNumPasses);
    HRESULT (WINAPI *GetInfo)(IDirect3DDevice8 *This, DWORD DevInfoID,void * pDevInfoStruct,DWORD DevInfoStructSize);
    HRESULT (WINAPI *SetPaletteEntries)(IDirect3DDevice8 *This, UINT palette_idx, const PALETTEENTRY *entries);
    HRESULT (WINAPI *GetPaletteEntries)(IDirect3DDevice8 *This, UINT PaletteNumber,PALETTEENTRY * pEntries);
    HRESULT (WINAPI *SetCurrentTexturePalette)(IDirect3DDevice8 *This, UINT PaletteNumber);
    HRESULT (WINAPI *GetCurrentTexturePalette)(IDirect3DDevice8 *This, UINT * PaletteNumber);
    HRESULT (WINAPI *DrawPrimitive)(IDirect3DDevice8 *This, D3DPRIMITIVETYPE PrimitiveType,UINT StartVertex,UINT PrimitiveCount);
    HRESULT (WINAPI *DrawIndexedPrimitive)(IDirect3DDevice8 *This, D3DPRIMITIVETYPE PrimitiveType,UINT minIndex,UINT NumVertices,UINT startIndex,UINT primCount);
    HRESULT (WINAPI *DrawPrimitiveUP)(IDirect3DDevice8 *This, D3DPRIMITIVETYPE primitive_type, UINT primitive_count, const void *data, UINT stride);
    HRESULT (WINAPI *DrawIndexedPrimitiveUP)(IDirect3DDevice8 *This, D3DPRIMITIVETYPE primitive_type, UINT min_vertex_idx, UINT vertex_count, UINT primitive_count, const void *index_data, D3DFORMAT index_format, const void *data, UINT stride);
    HRESULT (WINAPI *ProcessVertices)(IDirect3DDevice8 *This, UINT SrcStartIndex,UINT DestIndex,UINT VertexCount,IDirect3DVertexBuffer8 * pDestBuffer,DWORD Flags);
    HRESULT (WINAPI *CreateVertexShader)(IDirect3DDevice8 *This, const DWORD *declaration, const DWORD *byte_code, DWORD *shader, DWORD usage);
    HRESULT (WINAPI *SetVertexShader)(IDirect3DDevice8 *This, DWORD Handle);
    HRESULT (WINAPI *GetVertexShader)(IDirect3DDevice8 *This, DWORD * pHandle);
    HRESULT (WINAPI *DeleteVertexShader)(IDirect3DDevice8 *This, DWORD Handle);
    HRESULT (WINAPI *SetVertexShaderConstant)(IDirect3DDevice8 *This, DWORD reg_idx, const void *data, DWORD count);
    HRESULT (WINAPI *GetVertexShaderConstant)(IDirect3DDevice8 *This, DWORD Register,void * pConstantData,DWORD ConstantCount);
    HRESULT (WINAPI *GetVertexShaderDeclaration)(IDirect3DDevice8 *This, DWORD Handle,void * pData,DWORD * pSizeOfData);
    HRESULT (WINAPI *GetVertexShaderFunction)(IDirect3DDevice8 *This, DWORD Handle,void * pData,DWORD * pSizeOfData);
    HRESULT (WINAPI *SetStreamSource)(IDirect3DDevice8 *This, UINT StreamNumber,IDirect3DVertexBuffer8 * pStreamData,UINT Stride);
    HRESULT (WINAPI *GetStreamSource)(IDirect3DDevice8 *This, UINT StreamNumber,IDirect3DVertexBuffer8 ** ppStreamData,UINT * pStride);
    HRESULT (WINAPI *SetIndices)(IDirect3DDevice8 *This, IDirect3DIndexBuffer8 * pIndexData,UINT BaseVertexIndex);
    HRESULT (WINAPI *GetIndices)(IDirect3DDevice8 *This, IDirect3DIndexBuffer8 ** ppIndexData,UINT * pBaseVertexIndex);
    HRESULT (WINAPI *CreatePixelShader)(IDirect3DDevice8 *This, const DWORD *byte_code, DWORD *shader);
    HRESULT (WINAPI *SetPixelShader)(IDirect3DDevice8 *This, DWORD Handle);
    HRESULT (WINAPI *GetPixelShader)(IDirect3DDevice8 *This, DWORD * pHandle);
    HRESULT (WINAPI *DeletePixelShader)(IDirect3DDevice8 *This, DWORD Handle);
    HRESULT (WINAPI *SetPixelShaderConstant)(IDirect3DDevice8 *This, DWORD reg_idx, const void *data, DWORD count);
    HRESULT (WINAPI *GetPixelShaderConstant)(IDirect3DDevice8 *This, DWORD Register,void * pConstantData,DWORD ConstantCount);
    HRESULT (WINAPI *GetPixelShaderFunction)(IDirect3DDevice8 *This, DWORD Handle,void * pData,DWORD * pSizeOfData);
    HRESULT (WINAPI *DrawRectPatch)(IDirect3DDevice8 *This, UINT handle, const float *segment_count, const D3DRECTPATCH_INFO *patch_info);
    HRESULT (WINAPI *DrawTriPatch)(IDirect3DDevice8 *This, UINT handle, const float *segment_count, const D3DTRIPATCH_INFO *patch_info);
    HRESULT (WINAPI *DeletePatch)(IDirect3DDevice8 *This, UINT Handle);
} IDirect3DDevice8Vtbl;
struct IDirect3DDevice8 { const IDirect3DDevice8Vtbl *lpVtbl; };
/* --- IDirect3DDevice8: 97 methods --- */
HRESULT WINAPI dev8_QueryInterface(IDirect3DDevice8 *This, REFIID riid, void** ppvObject);
ULONG WINAPI dev8_AddRef(IDirect3DDevice8 *This);
ULONG WINAPI dev8_Release(IDirect3DDevice8 *This);
HRESULT WINAPI dev8_TestCooperativeLevel(IDirect3DDevice8 *This);
UINT WINAPI dev8_GetAvailableTextureMem(IDirect3DDevice8 *This);
HRESULT WINAPI dev8_ResourceManagerDiscardBytes(IDirect3DDevice8 *This, DWORD Bytes);
HRESULT WINAPI dev8_GetDirect3D(IDirect3DDevice8 *This, IDirect3D8 ** ppD3D8);
HRESULT WINAPI dev8_GetDeviceCaps(IDirect3DDevice8 *This, D3DCAPS8 * pCaps);
HRESULT WINAPI dev8_GetDisplayMode(IDirect3DDevice8 *This, D3DDISPLAYMODE * pMode);
HRESULT WINAPI dev8_GetCreationParameters(IDirect3DDevice8 *This, D3DDEVICE_CREATION_PARAMETERS * pParameters);
HRESULT WINAPI dev8_SetCursorProperties(IDirect3DDevice8 *This, UINT XHotSpot, UINT YHotSpot, IDirect3DSurface8 * pCursorBitmap);
void WINAPI dev8_SetCursorPosition(IDirect3DDevice8 *This, UINT XScreenSpace, UINT YScreenSpace,DWORD Flags);
WINBOOL WINAPI dev8_ShowCursor(IDirect3DDevice8 *This, WINBOOL bShow);
static HRESULT WINAPI dev8_CreateAdditionalSwapChain(IDirect3DDevice8 *This, D3DPRESENT_PARAMETERS8 * pPresentationParameters, IDirect3DSwapChain8 ** pSwapChain) { D3DPT_STUB("IDirect3DDevice8::CreateAdditionalSwapChain"); return E_NOTIMPL; }
HRESULT WINAPI dev8_Reset(IDirect3DDevice8 *This, D3DPRESENT_PARAMETERS8 * pPresentationParameters);
HRESULT WINAPI dev8_Present(IDirect3DDevice8 *This, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region);
HRESULT WINAPI dev8_GetBackBuffer(IDirect3DDevice8 *This, UINT BackBuffer,D3DBACKBUFFER_TYPE Type,IDirect3DSurface8 ** ppBackBuffer);
HRESULT WINAPI dev8_GetRasterStatus(IDirect3DDevice8 *This, D3DRASTER_STATUS * pRasterStatus);
void WINAPI dev8_SetGammaRamp(IDirect3DDevice8 *This, DWORD flags, const D3DGAMMARAMP *ramp);
void WINAPI dev8_GetGammaRamp(IDirect3DDevice8 *This, D3DGAMMARAMP * pRamp);
HRESULT WINAPI dev8_CreateTexture(IDirect3DDevice8 *This, UINT Width,UINT Height,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DTexture8 ** ppTexture);
static HRESULT WINAPI dev8_CreateVolumeTexture(IDirect3DDevice8 *This, UINT Width,UINT Height,UINT Depth,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DVolumeTexture8 ** ppVolumeTexture) { D3DPT_STUB("IDirect3DDevice8::CreateVolumeTexture"); return E_NOTIMPL; }
HRESULT WINAPI dev8_CreateCubeTexture(IDirect3DDevice8 *This, UINT EdgeLength,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DCubeTexture8 ** ppCubeTexture);
HRESULT WINAPI dev8_CreateVertexBuffer(IDirect3DDevice8 *This, UINT Length,DWORD Usage,DWORD FVF,D3DPOOL Pool,IDirect3DVertexBuffer8 ** ppVertexBuffer);
HRESULT WINAPI dev8_CreateIndexBuffer(IDirect3DDevice8 *This, UINT Length,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DIndexBuffer8 ** ppIndexBuffer);
HRESULT WINAPI dev8_CreateRenderTarget(IDirect3DDevice8 *This, UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,WINBOOL Lockable,IDirect3DSurface8 ** ppSurface);
HRESULT WINAPI dev8_CreateDepthStencilSurface(IDirect3DDevice8 *This, UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,IDirect3DSurface8 ** ppSurface);
HRESULT WINAPI dev8_CreateImageSurface(IDirect3DDevice8 *This, UINT Width,UINT Height,D3DFORMAT Format,IDirect3DSurface8 ** ppSurface);
HRESULT WINAPI dev8_CopyRects(IDirect3DDevice8 *This, IDirect3DSurface8 *src_surface, const RECT *src_rects, UINT rect_count, IDirect3DSurface8 *dst_surface, const POINT *dst_points);
HRESULT WINAPI dev8_UpdateTexture(IDirect3DDevice8 *This, IDirect3DBaseTexture8 * pSourceTexture,IDirect3DBaseTexture8 * pDestinationTexture);
static HRESULT WINAPI dev8_GetFrontBuffer(IDirect3DDevice8 *This, IDirect3DSurface8 * pDestSurface) { D3DPT_STUB("IDirect3DDevice8::GetFrontBuffer"); return E_NOTIMPL; }
HRESULT WINAPI dev8_SetRenderTarget(IDirect3DDevice8 *This, IDirect3DSurface8 * pRenderTarget,IDirect3DSurface8 * pNewZStencil);
HRESULT WINAPI dev8_GetRenderTarget(IDirect3DDevice8 *This, IDirect3DSurface8 ** ppRenderTarget);
HRESULT WINAPI dev8_GetDepthStencilSurface(IDirect3DDevice8 *This, IDirect3DSurface8 ** ppZStencilSurface);
HRESULT WINAPI dev8_BeginScene(IDirect3DDevice8 *This);
HRESULT WINAPI dev8_EndScene(IDirect3DDevice8 *This);
HRESULT WINAPI dev8_Clear(IDirect3DDevice8 *This, DWORD rect_count, const D3DRECT *rects, DWORD flags, D3DCOLOR color, float z, DWORD stencil);
HRESULT WINAPI dev8_SetTransform(IDirect3DDevice8 *This, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix);
HRESULT WINAPI dev8_GetTransform(IDirect3DDevice8 *This, D3DTRANSFORMSTATETYPE State,D3DMATRIX * pMatrix);
HRESULT WINAPI dev8_MultiplyTransform(IDirect3DDevice8 *This, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix);
HRESULT WINAPI dev8_SetViewport(IDirect3DDevice8 *This, const D3DVIEWPORT9 *viewport);
HRESULT WINAPI dev8_GetViewport(IDirect3DDevice8 *This, D3DVIEWPORT9 * pViewport);
HRESULT WINAPI dev8_SetMaterial(IDirect3DDevice8 *This, const D3DMATERIAL9 *material);
HRESULT WINAPI dev8_GetMaterial(IDirect3DDevice8 *This, D3DMATERIAL9 *pMaterial);
HRESULT WINAPI dev8_SetLight(IDirect3DDevice8 *This, DWORD index, const D3DLIGHT9 *light);
HRESULT WINAPI dev8_GetLight(IDirect3DDevice8 *This, DWORD Index,D3DLIGHT9 * pLight);
HRESULT WINAPI dev8_LightEnable(IDirect3DDevice8 *This, DWORD Index,WINBOOL Enable);
HRESULT WINAPI dev8_GetLightEnable(IDirect3DDevice8 *This, DWORD Index,WINBOOL * pEnable);
HRESULT WINAPI dev8_SetClipPlane(IDirect3DDevice8 *This, DWORD index, const float *plane);
HRESULT WINAPI dev8_GetClipPlane(IDirect3DDevice8 *This, DWORD Index,float * pPlane);
HRESULT WINAPI dev8_SetRenderState(IDirect3DDevice8 *This, D3DRENDERSTATETYPE State,DWORD Value);
HRESULT WINAPI dev8_GetRenderState(IDirect3DDevice8 *This, D3DRENDERSTATETYPE State,DWORD * pValue);
HRESULT WINAPI dev8_BeginStateBlock(IDirect3DDevice8 *This);
HRESULT WINAPI dev8_EndStateBlock(IDirect3DDevice8 *This, DWORD * pToken);
HRESULT WINAPI dev8_ApplyStateBlock(IDirect3DDevice8 *This, DWORD Token);
HRESULT WINAPI dev8_CaptureStateBlock(IDirect3DDevice8 *This, DWORD Token);
HRESULT WINAPI dev8_DeleteStateBlock(IDirect3DDevice8 *This, DWORD Token);
HRESULT WINAPI dev8_CreateStateBlock(IDirect3DDevice8 *This, D3DSTATEBLOCKTYPE Type,DWORD * pToken);
static HRESULT WINAPI dev8_SetClipStatus(IDirect3DDevice8 *This, const D3DCLIPSTATUS8 *clip_status) { D3DPT_STUB("IDirect3DDevice8::SetClipStatus"); return E_NOTIMPL; }
static HRESULT WINAPI dev8_GetClipStatus(IDirect3DDevice8 *This, D3DCLIPSTATUS8 * pClipStatus) { D3DPT_STUB("IDirect3DDevice8::GetClipStatus"); return E_NOTIMPL; }
HRESULT WINAPI dev8_GetTexture(IDirect3DDevice8 *This, DWORD Stage,IDirect3DBaseTexture8 ** ppTexture);
HRESULT WINAPI dev8_SetTexture(IDirect3DDevice8 *This, DWORD Stage,IDirect3DBaseTexture8 * pTexture);
HRESULT WINAPI dev8_GetTextureStageState(IDirect3DDevice8 *This, DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD * pValue);
HRESULT WINAPI dev8_SetTextureStageState(IDirect3DDevice8 *This, DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD Value);
HRESULT WINAPI dev8_ValidateDevice(IDirect3DDevice8 *This, DWORD * pNumPasses);
HRESULT WINAPI dev8_GetInfo(IDirect3DDevice8 *This, DWORD DevInfoID,void * pDevInfoStruct,DWORD DevInfoStructSize);
static HRESULT WINAPI dev8_SetPaletteEntries(IDirect3DDevice8 *This, UINT palette_idx, const PALETTEENTRY *entries) { D3DPT_STUB("IDirect3DDevice8::SetPaletteEntries"); return E_NOTIMPL; }
static HRESULT WINAPI dev8_GetPaletteEntries(IDirect3DDevice8 *This, UINT PaletteNumber,PALETTEENTRY * pEntries) { D3DPT_STUB("IDirect3DDevice8::GetPaletteEntries"); return E_NOTIMPL; }
static HRESULT WINAPI dev8_SetCurrentTexturePalette(IDirect3DDevice8 *This, UINT PaletteNumber) { D3DPT_STUB("IDirect3DDevice8::SetCurrentTexturePalette"); return E_NOTIMPL; }
static HRESULT WINAPI dev8_GetCurrentTexturePalette(IDirect3DDevice8 *This, UINT * PaletteNumber) { D3DPT_STUB("IDirect3DDevice8::GetCurrentTexturePalette"); return E_NOTIMPL; }
HRESULT WINAPI dev8_DrawPrimitive(IDirect3DDevice8 *This, D3DPRIMITIVETYPE PrimitiveType,UINT StartVertex,UINT PrimitiveCount);
HRESULT WINAPI dev8_DrawIndexedPrimitive(IDirect3DDevice8 *This, D3DPRIMITIVETYPE PrimitiveType,UINT minIndex,UINT NumVertices,UINT startIndex,UINT primCount);
HRESULT WINAPI dev8_DrawPrimitiveUP(IDirect3DDevice8 *This, D3DPRIMITIVETYPE primitive_type, UINT primitive_count, const void *data, UINT stride);
HRESULT WINAPI dev8_DrawIndexedPrimitiveUP(IDirect3DDevice8 *This, D3DPRIMITIVETYPE primitive_type, UINT min_vertex_idx, UINT vertex_count, UINT primitive_count, const void *index_data, D3DFORMAT index_format, const void *data, UINT stride);
static HRESULT WINAPI dev8_ProcessVertices(IDirect3DDevice8 *This, UINT SrcStartIndex,UINT DestIndex,UINT VertexCount,IDirect3DVertexBuffer8 * pDestBuffer,DWORD Flags) { D3DPT_STUB("IDirect3DDevice8::ProcessVertices"); return E_NOTIMPL; }
HRESULT WINAPI dev8_CreateVertexShader(IDirect3DDevice8 *This, const DWORD *declaration, const DWORD *byte_code, DWORD *shader, DWORD usage);
HRESULT WINAPI dev8_SetVertexShader(IDirect3DDevice8 *This, DWORD Handle);
HRESULT WINAPI dev8_GetVertexShader(IDirect3DDevice8 *This, DWORD * pHandle);
HRESULT WINAPI dev8_DeleteVertexShader(IDirect3DDevice8 *This, DWORD Handle);
HRESULT WINAPI dev8_SetVertexShaderConstant(IDirect3DDevice8 *This, DWORD reg_idx, const void *data, DWORD count);
HRESULT WINAPI dev8_GetVertexShaderConstant(IDirect3DDevice8 *This, DWORD Register,void * pConstantData,DWORD ConstantCount);
HRESULT WINAPI dev8_GetVertexShaderDeclaration(IDirect3DDevice8 *This, DWORD Handle,void * pData,DWORD * pSizeOfData);
HRESULT WINAPI dev8_GetVertexShaderFunction(IDirect3DDevice8 *This, DWORD Handle,void * pData,DWORD * pSizeOfData);
HRESULT WINAPI dev8_SetStreamSource(IDirect3DDevice8 *This, UINT StreamNumber,IDirect3DVertexBuffer8 * pStreamData,UINT Stride);
HRESULT WINAPI dev8_GetStreamSource(IDirect3DDevice8 *This, UINT StreamNumber,IDirect3DVertexBuffer8 ** ppStreamData,UINT * pStride);
HRESULT WINAPI dev8_SetIndices(IDirect3DDevice8 *This, IDirect3DIndexBuffer8 * pIndexData,UINT BaseVertexIndex);
HRESULT WINAPI dev8_GetIndices(IDirect3DDevice8 *This, IDirect3DIndexBuffer8 ** ppIndexData,UINT * pBaseVertexIndex);
HRESULT WINAPI dev8_CreatePixelShader(IDirect3DDevice8 *This, const DWORD *byte_code, DWORD *shader);
HRESULT WINAPI dev8_SetPixelShader(IDirect3DDevice8 *This, DWORD Handle);
HRESULT WINAPI dev8_GetPixelShader(IDirect3DDevice8 *This, DWORD * pHandle);
HRESULT WINAPI dev8_DeletePixelShader(IDirect3DDevice8 *This, DWORD Handle);
HRESULT WINAPI dev8_SetPixelShaderConstant(IDirect3DDevice8 *This, DWORD reg_idx, const void *data, DWORD count);
HRESULT WINAPI dev8_GetPixelShaderConstant(IDirect3DDevice8 *This, DWORD Register,void * pConstantData,DWORD ConstantCount);
HRESULT WINAPI dev8_GetPixelShaderFunction(IDirect3DDevice8 *This, DWORD Handle,void * pData,DWORD * pSizeOfData);
static HRESULT WINAPI dev8_DrawRectPatch(IDirect3DDevice8 *This, UINT handle, const float *segment_count, const D3DRECTPATCH_INFO *patch_info) { D3DPT_STUB("IDirect3DDevice8::DrawRectPatch"); return E_NOTIMPL; }
static HRESULT WINAPI dev8_DrawTriPatch(IDirect3DDevice8 *This, UINT handle, const float *segment_count, const D3DTRIPATCH_INFO *patch_info) { D3DPT_STUB("IDirect3DDevice8::DrawTriPatch"); return E_NOTIMPL; }
static HRESULT WINAPI dev8_DeletePatch(IDirect3DDevice8 *This, UINT Handle) { D3DPT_STUB("IDirect3DDevice8::DeletePatch"); return E_NOTIMPL; }
static const IDirect3DDevice8Vtbl dev8_vtbl = {
    dev8_QueryInterface,
    dev8_AddRef,
    dev8_Release,
    dev8_TestCooperativeLevel,
    dev8_GetAvailableTextureMem,
    dev8_ResourceManagerDiscardBytes,
    dev8_GetDirect3D,
    dev8_GetDeviceCaps,
    dev8_GetDisplayMode,
    dev8_GetCreationParameters,
    dev8_SetCursorProperties,
    dev8_SetCursorPosition,
    dev8_ShowCursor,
    dev8_CreateAdditionalSwapChain,
    dev8_Reset,
    dev8_Present,
    dev8_GetBackBuffer,
    dev8_GetRasterStatus,
    dev8_SetGammaRamp,
    dev8_GetGammaRamp,
    dev8_CreateTexture,
    dev8_CreateVolumeTexture,
    dev8_CreateCubeTexture,
    dev8_CreateVertexBuffer,
    dev8_CreateIndexBuffer,
    dev8_CreateRenderTarget,
    dev8_CreateDepthStencilSurface,
    dev8_CreateImageSurface,
    dev8_CopyRects,
    dev8_UpdateTexture,
    dev8_GetFrontBuffer,
    dev8_SetRenderTarget,
    dev8_GetRenderTarget,
    dev8_GetDepthStencilSurface,
    dev8_BeginScene,
    dev8_EndScene,
    dev8_Clear,
    dev8_SetTransform,
    dev8_GetTransform,
    dev8_MultiplyTransform,
    dev8_SetViewport,
    dev8_GetViewport,
    dev8_SetMaterial,
    dev8_GetMaterial,
    dev8_SetLight,
    dev8_GetLight,
    dev8_LightEnable,
    dev8_GetLightEnable,
    dev8_SetClipPlane,
    dev8_GetClipPlane,
    dev8_SetRenderState,
    dev8_GetRenderState,
    dev8_BeginStateBlock,
    dev8_EndStateBlock,
    dev8_ApplyStateBlock,
    dev8_CaptureStateBlock,
    dev8_DeleteStateBlock,
    dev8_CreateStateBlock,
    dev8_SetClipStatus,
    dev8_GetClipStatus,
    dev8_GetTexture,
    dev8_SetTexture,
    dev8_GetTextureStageState,
    dev8_SetTextureStageState,
    dev8_ValidateDevice,
    dev8_GetInfo,
    dev8_SetPaletteEntries,
    dev8_GetPaletteEntries,
    dev8_SetCurrentTexturePalette,
    dev8_GetCurrentTexturePalette,
    dev8_DrawPrimitive,
    dev8_DrawIndexedPrimitive,
    dev8_DrawPrimitiveUP,
    dev8_DrawIndexedPrimitiveUP,
    dev8_ProcessVertices,
    dev8_CreateVertexShader,
    dev8_SetVertexShader,
    dev8_GetVertexShader,
    dev8_DeleteVertexShader,
    dev8_SetVertexShaderConstant,
    dev8_GetVertexShaderConstant,
    dev8_GetVertexShaderDeclaration,
    dev8_GetVertexShaderFunction,
    dev8_SetStreamSource,
    dev8_GetStreamSource,
    dev8_SetIndices,
    dev8_GetIndices,
    dev8_CreatePixelShader,
    dev8_SetPixelShader,
    dev8_GetPixelShader,
    dev8_DeletePixelShader,
    dev8_SetPixelShaderConstant,
    dev8_GetPixelShaderConstant,
    dev8_GetPixelShaderFunction,
    dev8_DrawRectPatch,
    dev8_DrawTriPatch,
    dev8_DeletePatch,
};

typedef struct IDirect3DSurface8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DSurface8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DSurface8 *This);
    ULONG (WINAPI *Release)(IDirect3DSurface8 *This);
    HRESULT (WINAPI *GetDevice)(IDirect3DSurface8 *This, IDirect3DDevice8 ** ppDevice);
    HRESULT (WINAPI *SetPrivateData)(IDirect3DSurface8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
    HRESULT (WINAPI *GetPrivateData)(IDirect3DSurface8 *This, REFGUID refguid,void * pData,DWORD * pSizeOfData);
    HRESULT (WINAPI *FreePrivateData)(IDirect3DSurface8 *This, REFGUID refguid);
    HRESULT (WINAPI *GetContainer)(IDirect3DSurface8 *This, REFIID riid, void ** ppContainer);
    HRESULT (WINAPI *GetDesc)(IDirect3DSurface8 *This, D3DSURFACE_DESC8 * pDesc);
    HRESULT (WINAPI *LockRect)(IDirect3DSurface8 *This, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
    HRESULT (WINAPI *UnlockRect)(IDirect3DSurface8 *This);
} IDirect3DSurface8Vtbl;
struct IDirect3DSurface8 { const IDirect3DSurface8Vtbl *lpVtbl; };
/* --- IDirect3DSurface8: 11 methods --- */
HRESULT WINAPI surf8_QueryInterface(IDirect3DSurface8 *This, REFIID riid, void** ppvObject);
ULONG WINAPI surf8_AddRef(IDirect3DSurface8 *This);
ULONG WINAPI surf8_Release(IDirect3DSurface8 *This);
HRESULT WINAPI surf8_GetDevice(IDirect3DSurface8 *This, IDirect3DDevice8 ** ppDevice);
HRESULT WINAPI surf8_SetPrivateData(IDirect3DSurface8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
HRESULT WINAPI surf8_GetPrivateData(IDirect3DSurface8 *This, REFGUID refguid,void * pData,DWORD * pSizeOfData);
HRESULT WINAPI surf8_FreePrivateData(IDirect3DSurface8 *This, REFGUID refguid);
HRESULT WINAPI surf8_GetContainer(IDirect3DSurface8 *This, REFIID riid, void ** ppContainer);
HRESULT WINAPI surf8_GetDesc(IDirect3DSurface8 *This, D3DSURFACE_DESC8 * pDesc);
HRESULT WINAPI surf8_LockRect(IDirect3DSurface8 *This, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
HRESULT WINAPI surf8_UnlockRect(IDirect3DSurface8 *This);
static const IDirect3DSurface8Vtbl surf8_vtbl = {
    surf8_QueryInterface,
    surf8_AddRef,
    surf8_Release,
    surf8_GetDevice,
    surf8_SetPrivateData,
    surf8_GetPrivateData,
    surf8_FreePrivateData,
    surf8_GetContainer,
    surf8_GetDesc,
    surf8_LockRect,
    surf8_UnlockRect,
};

typedef struct IDirect3DTexture8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DTexture8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DTexture8 *This);
    ULONG (WINAPI *Release)(IDirect3DTexture8 *This);
    HRESULT (WINAPI *GetDevice)(IDirect3DTexture8 *This, IDirect3DDevice8 ** ppDevice);
    HRESULT (WINAPI *SetPrivateData)(IDirect3DTexture8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
    HRESULT (WINAPI *GetPrivateData)(IDirect3DTexture8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
    HRESULT (WINAPI *FreePrivateData)(IDirect3DTexture8 *This, REFGUID refguid);
    DWORD (WINAPI *SetPriority)(IDirect3DTexture8 *This, DWORD PriorityNew);
    DWORD (WINAPI *GetPriority)(IDirect3DTexture8 *This);
    void (WINAPI *PreLoad)(IDirect3DTexture8 *This);
    D3DRESOURCETYPE (WINAPI *GetType)(IDirect3DTexture8 *This);
    DWORD (WINAPI *SetLOD)(IDirect3DTexture8 *This, DWORD LODNew);
    DWORD (WINAPI *GetLOD)(IDirect3DTexture8 *This);
    DWORD (WINAPI *GetLevelCount)(IDirect3DTexture8 *This);
    HRESULT (WINAPI *GetLevelDesc)(IDirect3DTexture8 *This, UINT Level,D3DSURFACE_DESC8 * pDesc);
    HRESULT (WINAPI *GetSurfaceLevel)(IDirect3DTexture8 *This, UINT Level,IDirect3DSurface8 ** ppSurfaceLevel);
    HRESULT (WINAPI *LockRect)(IDirect3DTexture8 *This, UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
    HRESULT (WINAPI *UnlockRect)(IDirect3DTexture8 *This, UINT Level);
    HRESULT (WINAPI *AddDirtyRect)(IDirect3DTexture8 *This, const RECT *dirty_rect);
} IDirect3DTexture8Vtbl;
struct IDirect3DTexture8 { const IDirect3DTexture8Vtbl *lpVtbl; };
/* --- IDirect3DTexture8: 19 methods --- */
HRESULT WINAPI tex8_QueryInterface(IDirect3DTexture8 *This, REFIID riid, void** ppvObject);
ULONG WINAPI tex8_AddRef(IDirect3DTexture8 *This);
ULONG WINAPI tex8_Release(IDirect3DTexture8 *This);
HRESULT WINAPI tex8_GetDevice(IDirect3DTexture8 *This, IDirect3DDevice8 ** ppDevice);
HRESULT WINAPI tex8_SetPrivateData(IDirect3DTexture8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
HRESULT WINAPI tex8_GetPrivateData(IDirect3DTexture8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
HRESULT WINAPI tex8_FreePrivateData(IDirect3DTexture8 *This, REFGUID refguid);
DWORD WINAPI tex8_SetPriority(IDirect3DTexture8 *This, DWORD PriorityNew);
DWORD WINAPI tex8_GetPriority(IDirect3DTexture8 *This);
void WINAPI tex8_PreLoad(IDirect3DTexture8 *This);
D3DRESOURCETYPE WINAPI tex8_GetType(IDirect3DTexture8 *This);
DWORD WINAPI tex8_SetLOD(IDirect3DTexture8 *This, DWORD LODNew);
DWORD WINAPI tex8_GetLOD(IDirect3DTexture8 *This);
DWORD WINAPI tex8_GetLevelCount(IDirect3DTexture8 *This);
HRESULT WINAPI tex8_GetLevelDesc(IDirect3DTexture8 *This, UINT Level,D3DSURFACE_DESC8 * pDesc);
HRESULT WINAPI tex8_GetSurfaceLevel(IDirect3DTexture8 *This, UINT Level,IDirect3DSurface8 ** ppSurfaceLevel);
HRESULT WINAPI tex8_LockRect(IDirect3DTexture8 *This, UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
HRESULT WINAPI tex8_UnlockRect(IDirect3DTexture8 *This, UINT Level);
HRESULT WINAPI tex8_AddDirtyRect(IDirect3DTexture8 *This, const RECT *dirty_rect);
static const IDirect3DTexture8Vtbl tex8_vtbl = {
    tex8_QueryInterface,
    tex8_AddRef,
    tex8_Release,
    tex8_GetDevice,
    tex8_SetPrivateData,
    tex8_GetPrivateData,
    tex8_FreePrivateData,
    tex8_SetPriority,
    tex8_GetPriority,
    tex8_PreLoad,
    tex8_GetType,
    tex8_SetLOD,
    tex8_GetLOD,
    tex8_GetLevelCount,
    tex8_GetLevelDesc,
    tex8_GetSurfaceLevel,
    tex8_LockRect,
    tex8_UnlockRect,
    tex8_AddDirtyRect,
};

typedef struct IDirect3DCubeTexture8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DCubeTexture8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DCubeTexture8 *This);
    ULONG (WINAPI *Release)(IDirect3DCubeTexture8 *This);
    HRESULT (WINAPI *GetDevice)(IDirect3DCubeTexture8 *This, IDirect3DDevice8 ** ppDevice);
    HRESULT (WINAPI *SetPrivateData)(IDirect3DCubeTexture8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
    HRESULT (WINAPI *GetPrivateData)(IDirect3DCubeTexture8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
    HRESULT (WINAPI *FreePrivateData)(IDirect3DCubeTexture8 *This, REFGUID refguid);
    DWORD (WINAPI *SetPriority)(IDirect3DCubeTexture8 *This, DWORD PriorityNew);
    DWORD (WINAPI *GetPriority)(IDirect3DCubeTexture8 *This);
    void (WINAPI *PreLoad)(IDirect3DCubeTexture8 *This);
    D3DRESOURCETYPE (WINAPI *GetType)(IDirect3DCubeTexture8 *This);
    DWORD (WINAPI *SetLOD)(IDirect3DCubeTexture8 *This, DWORD LODNew);
    DWORD (WINAPI *GetLOD)(IDirect3DCubeTexture8 *This);
    DWORD (WINAPI *GetLevelCount)(IDirect3DCubeTexture8 *This);
    HRESULT (WINAPI *GetLevelDesc)(IDirect3DCubeTexture8 *This, UINT Level,D3DSURFACE_DESC8 * pDesc);
    HRESULT (WINAPI *GetCubeMapSurface)(IDirect3DCubeTexture8 *This, D3DCUBEMAP_FACES FaceType,UINT Level,IDirect3DSurface8 ** ppCubeMapSurface);
    HRESULT (WINAPI *LockRect)(IDirect3DCubeTexture8 *This, D3DCUBEMAP_FACES face, UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
    HRESULT (WINAPI *UnlockRect)(IDirect3DCubeTexture8 *This, D3DCUBEMAP_FACES FaceType,UINT Level);
    HRESULT (WINAPI *AddDirtyRect)(IDirect3DCubeTexture8 *This, D3DCUBEMAP_FACES face, const RECT *dirty_rect);
} IDirect3DCubeTexture8Vtbl;
struct IDirect3DCubeTexture8 { const IDirect3DCubeTexture8Vtbl *lpVtbl; };
/* --- IDirect3DCubeTexture8: 19 methods --- */
HRESULT WINAPI cube8_QueryInterface(IDirect3DCubeTexture8 *This, REFIID riid, void** ppvObject);
ULONG WINAPI cube8_AddRef(IDirect3DCubeTexture8 *This);
ULONG WINAPI cube8_Release(IDirect3DCubeTexture8 *This);
HRESULT WINAPI cube8_GetDevice(IDirect3DCubeTexture8 *This, IDirect3DDevice8 ** ppDevice);
HRESULT WINAPI cube8_SetPrivateData(IDirect3DCubeTexture8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
HRESULT WINAPI cube8_GetPrivateData(IDirect3DCubeTexture8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
HRESULT WINAPI cube8_FreePrivateData(IDirect3DCubeTexture8 *This, REFGUID refguid);
DWORD WINAPI cube8_SetPriority(IDirect3DCubeTexture8 *This, DWORD PriorityNew);
DWORD WINAPI cube8_GetPriority(IDirect3DCubeTexture8 *This);
void WINAPI cube8_PreLoad(IDirect3DCubeTexture8 *This);
D3DRESOURCETYPE WINAPI cube8_GetType(IDirect3DCubeTexture8 *This);
DWORD WINAPI cube8_SetLOD(IDirect3DCubeTexture8 *This, DWORD LODNew);
DWORD WINAPI cube8_GetLOD(IDirect3DCubeTexture8 *This);
DWORD WINAPI cube8_GetLevelCount(IDirect3DCubeTexture8 *This);
HRESULT WINAPI cube8_GetLevelDesc(IDirect3DCubeTexture8 *This, UINT Level,D3DSURFACE_DESC8 * pDesc);
HRESULT WINAPI cube8_GetCubeMapSurface(IDirect3DCubeTexture8 *This, D3DCUBEMAP_FACES FaceType,UINT Level,IDirect3DSurface8 ** ppCubeMapSurface);
HRESULT WINAPI cube8_LockRect(IDirect3DCubeTexture8 *This, D3DCUBEMAP_FACES face, UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags);
HRESULT WINAPI cube8_UnlockRect(IDirect3DCubeTexture8 *This, D3DCUBEMAP_FACES FaceType,UINT Level);
HRESULT WINAPI cube8_AddDirtyRect(IDirect3DCubeTexture8 *This, D3DCUBEMAP_FACES face, const RECT *dirty_rect);
static const IDirect3DCubeTexture8Vtbl cube8_vtbl = {
    cube8_QueryInterface,
    cube8_AddRef,
    cube8_Release,
    cube8_GetDevice,
    cube8_SetPrivateData,
    cube8_GetPrivateData,
    cube8_FreePrivateData,
    cube8_SetPriority,
    cube8_GetPriority,
    cube8_PreLoad,
    cube8_GetType,
    cube8_SetLOD,
    cube8_GetLOD,
    cube8_GetLevelCount,
    cube8_GetLevelDesc,
    cube8_GetCubeMapSurface,
    cube8_LockRect,
    cube8_UnlockRect,
    cube8_AddDirtyRect,
};

typedef struct IDirect3DVertexBuffer8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DVertexBuffer8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DVertexBuffer8 *This);
    ULONG (WINAPI *Release)(IDirect3DVertexBuffer8 *This);
    HRESULT (WINAPI *GetDevice)(IDirect3DVertexBuffer8 *This, IDirect3DDevice8 ** ppDevice);
    HRESULT (WINAPI *SetPrivateData)(IDirect3DVertexBuffer8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
    HRESULT (WINAPI *GetPrivateData)(IDirect3DVertexBuffer8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
    HRESULT (WINAPI *FreePrivateData)(IDirect3DVertexBuffer8 *This, REFGUID refguid);
    DWORD (WINAPI *SetPriority)(IDirect3DVertexBuffer8 *This, DWORD PriorityNew);
    DWORD (WINAPI *GetPriority)(IDirect3DVertexBuffer8 *This);
    void (WINAPI *PreLoad)(IDirect3DVertexBuffer8 *This);
    D3DRESOURCETYPE (WINAPI *GetType)(IDirect3DVertexBuffer8 *This);
    HRESULT (WINAPI *Lock)(IDirect3DVertexBuffer8 *This, UINT OffsetToLock, UINT SizeToLock, BYTE ** ppbData, DWORD Flags);
    HRESULT (WINAPI *Unlock)(IDirect3DVertexBuffer8 *This);
    HRESULT (WINAPI *GetDesc)(IDirect3DVertexBuffer8 *This, D3DVERTEXBUFFER_DESC * pDesc);
} IDirect3DVertexBuffer8Vtbl;
struct IDirect3DVertexBuffer8 { const IDirect3DVertexBuffer8Vtbl *lpVtbl; };
/* --- IDirect3DVertexBuffer8: 14 methods --- */
HRESULT WINAPI vb8_QueryInterface(IDirect3DVertexBuffer8 *This, REFIID riid, void** ppvObject);
ULONG WINAPI vb8_AddRef(IDirect3DVertexBuffer8 *This);
ULONG WINAPI vb8_Release(IDirect3DVertexBuffer8 *This);
HRESULT WINAPI vb8_GetDevice(IDirect3DVertexBuffer8 *This, IDirect3DDevice8 ** ppDevice);
HRESULT WINAPI vb8_SetPrivateData(IDirect3DVertexBuffer8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
HRESULT WINAPI vb8_GetPrivateData(IDirect3DVertexBuffer8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
HRESULT WINAPI vb8_FreePrivateData(IDirect3DVertexBuffer8 *This, REFGUID refguid);
DWORD WINAPI vb8_SetPriority(IDirect3DVertexBuffer8 *This, DWORD PriorityNew);
DWORD WINAPI vb8_GetPriority(IDirect3DVertexBuffer8 *This);
void WINAPI vb8_PreLoad(IDirect3DVertexBuffer8 *This);
D3DRESOURCETYPE WINAPI vb8_GetType(IDirect3DVertexBuffer8 *This);
HRESULT WINAPI vb8_Lock(IDirect3DVertexBuffer8 *This, UINT OffsetToLock, UINT SizeToLock, BYTE ** ppbData, DWORD Flags);
HRESULT WINAPI vb8_Unlock(IDirect3DVertexBuffer8 *This);
HRESULT WINAPI vb8_GetDesc(IDirect3DVertexBuffer8 *This, D3DVERTEXBUFFER_DESC * pDesc);
static const IDirect3DVertexBuffer8Vtbl vb8_vtbl = {
    vb8_QueryInterface,
    vb8_AddRef,
    vb8_Release,
    vb8_GetDevice,
    vb8_SetPrivateData,
    vb8_GetPrivateData,
    vb8_FreePrivateData,
    vb8_SetPriority,
    vb8_GetPriority,
    vb8_PreLoad,
    vb8_GetType,
    vb8_Lock,
    vb8_Unlock,
    vb8_GetDesc,
};

typedef struct IDirect3DIndexBuffer8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DIndexBuffer8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DIndexBuffer8 *This);
    ULONG (WINAPI *Release)(IDirect3DIndexBuffer8 *This);
    HRESULT (WINAPI *GetDevice)(IDirect3DIndexBuffer8 *This, IDirect3DDevice8 ** ppDevice);
    HRESULT (WINAPI *SetPrivateData)(IDirect3DIndexBuffer8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
    HRESULT (WINAPI *GetPrivateData)(IDirect3DIndexBuffer8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
    HRESULT (WINAPI *FreePrivateData)(IDirect3DIndexBuffer8 *This, REFGUID refguid);
    DWORD (WINAPI *SetPriority)(IDirect3DIndexBuffer8 *This, DWORD PriorityNew);
    DWORD (WINAPI *GetPriority)(IDirect3DIndexBuffer8 *This);
    void (WINAPI *PreLoad)(IDirect3DIndexBuffer8 *This);
    D3DRESOURCETYPE (WINAPI *GetType)(IDirect3DIndexBuffer8 *This);
    HRESULT (WINAPI *Lock)(IDirect3DIndexBuffer8 *This, UINT OffsetToLock, UINT SizeToLock, BYTE ** ppbData, DWORD Flags);
    HRESULT (WINAPI *Unlock)(IDirect3DIndexBuffer8 *This);
    HRESULT (WINAPI *GetDesc)(IDirect3DIndexBuffer8 *This, D3DINDEXBUFFER_DESC * pDesc);
} IDirect3DIndexBuffer8Vtbl;
struct IDirect3DIndexBuffer8 { const IDirect3DIndexBuffer8Vtbl *lpVtbl; };
/* --- IDirect3DIndexBuffer8: 14 methods --- */
HRESULT WINAPI ib8_QueryInterface(IDirect3DIndexBuffer8 *This, REFIID riid, void** ppvObject);
ULONG WINAPI ib8_AddRef(IDirect3DIndexBuffer8 *This);
ULONG WINAPI ib8_Release(IDirect3DIndexBuffer8 *This);
HRESULT WINAPI ib8_GetDevice(IDirect3DIndexBuffer8 *This, IDirect3DDevice8 ** ppDevice);
HRESULT WINAPI ib8_SetPrivateData(IDirect3DIndexBuffer8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
HRESULT WINAPI ib8_GetPrivateData(IDirect3DIndexBuffer8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
HRESULT WINAPI ib8_FreePrivateData(IDirect3DIndexBuffer8 *This, REFGUID refguid);
DWORD WINAPI ib8_SetPriority(IDirect3DIndexBuffer8 *This, DWORD PriorityNew);
DWORD WINAPI ib8_GetPriority(IDirect3DIndexBuffer8 *This);
void WINAPI ib8_PreLoad(IDirect3DIndexBuffer8 *This);
D3DRESOURCETYPE WINAPI ib8_GetType(IDirect3DIndexBuffer8 *This);
HRESULT WINAPI ib8_Lock(IDirect3DIndexBuffer8 *This, UINT OffsetToLock, UINT SizeToLock, BYTE ** ppbData, DWORD Flags);
HRESULT WINAPI ib8_Unlock(IDirect3DIndexBuffer8 *This);
HRESULT WINAPI ib8_GetDesc(IDirect3DIndexBuffer8 *This, D3DINDEXBUFFER_DESC * pDesc);
static const IDirect3DIndexBuffer8Vtbl ib8_vtbl = {
    ib8_QueryInterface,
    ib8_AddRef,
    ib8_Release,
    ib8_GetDevice,
    ib8_SetPrivateData,
    ib8_GetPrivateData,
    ib8_FreePrivateData,
    ib8_SetPriority,
    ib8_GetPriority,
    ib8_PreLoad,
    ib8_GetType,
    ib8_Lock,
    ib8_Unlock,
    ib8_GetDesc,
};

typedef struct IDirect3DSwapChain8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DSwapChain8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DSwapChain8 *This);
    ULONG (WINAPI *Release)(IDirect3DSwapChain8 *This);
    HRESULT (WINAPI *Present)(IDirect3DSwapChain8 *This, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region);
    HRESULT (WINAPI *GetBackBuffer)(IDirect3DSwapChain8 *This, UINT BackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface8 ** ppBackBuffer);
} IDirect3DSwapChain8Vtbl;
struct IDirect3DSwapChain8 { const IDirect3DSwapChain8Vtbl *lpVtbl; };
/* --- IDirect3DSwapChain8: 5 methods --- */
static HRESULT WINAPI swap8_QueryInterface(IDirect3DSwapChain8 *This, REFIID riid, void** ppvObject) { D3DPT_STUB("IDirect3DSwapChain8::QueryInterface"); return E_NOTIMPL; }
static ULONG WINAPI swap8_AddRef(IDirect3DSwapChain8 *This) { D3DPT_STUB("IDirect3DSwapChain8::AddRef"); return 0; }
static ULONG WINAPI swap8_Release(IDirect3DSwapChain8 *This) { D3DPT_STUB("IDirect3DSwapChain8::Release"); return 0; }
static HRESULT WINAPI swap8_Present(IDirect3DSwapChain8 *This, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region) { D3DPT_STUB("IDirect3DSwapChain8::Present"); return E_NOTIMPL; }
static HRESULT WINAPI swap8_GetBackBuffer(IDirect3DSwapChain8 *This, UINT BackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface8 ** ppBackBuffer) { D3DPT_STUB("IDirect3DSwapChain8::GetBackBuffer"); return E_NOTIMPL; }
static const IDirect3DSwapChain8Vtbl swap8_vtbl = {
    swap8_QueryInterface,
    swap8_AddRef,
    swap8_Release,
    swap8_Present,
    swap8_GetBackBuffer,
};

typedef struct IDirect3DVolumeTexture8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DVolumeTexture8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DVolumeTexture8 *This);
    ULONG (WINAPI *Release)(IDirect3DVolumeTexture8 *This);
    HRESULT (WINAPI *GetDevice)(IDirect3DVolumeTexture8 *This, IDirect3DDevice8 ** ppDevice);
    HRESULT (WINAPI *SetPrivateData)(IDirect3DVolumeTexture8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
    HRESULT (WINAPI *GetPrivateData)(IDirect3DVolumeTexture8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
    HRESULT (WINAPI *FreePrivateData)(IDirect3DVolumeTexture8 *This, REFGUID refguid);
    DWORD (WINAPI *SetPriority)(IDirect3DVolumeTexture8 *This, DWORD PriorityNew);
    DWORD (WINAPI *GetPriority)(IDirect3DVolumeTexture8 *This);
    void (WINAPI *PreLoad)(IDirect3DVolumeTexture8 *This);
    D3DRESOURCETYPE (WINAPI *GetType)(IDirect3DVolumeTexture8 *This);
    DWORD (WINAPI *SetLOD)(IDirect3DVolumeTexture8 *This, DWORD LODNew);
    DWORD (WINAPI *GetLOD)(IDirect3DVolumeTexture8 *This);
    DWORD (WINAPI *GetLevelCount)(IDirect3DVolumeTexture8 *This);
    HRESULT (WINAPI *GetLevelDesc)(IDirect3DVolumeTexture8 *This, UINT Level,D3DVOLUME_DESC8 * pDesc);
    HRESULT (WINAPI *GetVolumeLevel)(IDirect3DVolumeTexture8 *This, UINT Level,IDirect3DVolume8 ** ppVolumeLevel);
    HRESULT (WINAPI *LockBox)(IDirect3DVolumeTexture8 *This, UINT level, D3DLOCKED_BOX *locked_box, const D3DBOX *box, DWORD flags);
    HRESULT (WINAPI *UnlockBox)(IDirect3DVolumeTexture8 *This, UINT Level);
    HRESULT (WINAPI *AddDirtyBox)(IDirect3DVolumeTexture8 *This, const D3DBOX *dirty_box);
} IDirect3DVolumeTexture8Vtbl;
struct IDirect3DVolumeTexture8 { const IDirect3DVolumeTexture8Vtbl *lpVtbl; };
/* --- IDirect3DVolumeTexture8: 19 methods --- */
static HRESULT WINAPI vtex8_QueryInterface(IDirect3DVolumeTexture8 *This, REFIID riid, void** ppvObject) { D3DPT_STUB("IDirect3DVolumeTexture8::QueryInterface"); return E_NOTIMPL; }
static ULONG WINAPI vtex8_AddRef(IDirect3DVolumeTexture8 *This) { D3DPT_STUB("IDirect3DVolumeTexture8::AddRef"); return 0; }
static ULONG WINAPI vtex8_Release(IDirect3DVolumeTexture8 *This) { D3DPT_STUB("IDirect3DVolumeTexture8::Release"); return 0; }
static HRESULT WINAPI vtex8_GetDevice(IDirect3DVolumeTexture8 *This, IDirect3DDevice8 ** ppDevice) { D3DPT_STUB("IDirect3DVolumeTexture8::GetDevice"); return E_NOTIMPL; }
static HRESULT WINAPI vtex8_SetPrivateData(IDirect3DVolumeTexture8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags) { D3DPT_STUB("IDirect3DVolumeTexture8::SetPrivateData"); return E_NOTIMPL; }
static HRESULT WINAPI vtex8_GetPrivateData(IDirect3DVolumeTexture8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData) { D3DPT_STUB("IDirect3DVolumeTexture8::GetPrivateData"); return E_NOTIMPL; }
static HRESULT WINAPI vtex8_FreePrivateData(IDirect3DVolumeTexture8 *This, REFGUID refguid) { D3DPT_STUB("IDirect3DVolumeTexture8::FreePrivateData"); return E_NOTIMPL; }
static DWORD WINAPI vtex8_SetPriority(IDirect3DVolumeTexture8 *This, DWORD PriorityNew) { D3DPT_STUB("IDirect3DVolumeTexture8::SetPriority"); return 0; }
static DWORD WINAPI vtex8_GetPriority(IDirect3DVolumeTexture8 *This) { D3DPT_STUB("IDirect3DVolumeTexture8::GetPriority"); return 0; }
static void WINAPI vtex8_PreLoad(IDirect3DVolumeTexture8 *This) { D3DPT_STUB("IDirect3DVolumeTexture8::PreLoad");  }
static D3DRESOURCETYPE WINAPI vtex8_GetType(IDirect3DVolumeTexture8 *This) { D3DPT_STUB("IDirect3DVolumeTexture8::GetType"); return 0; }
static DWORD WINAPI vtex8_SetLOD(IDirect3DVolumeTexture8 *This, DWORD LODNew) { D3DPT_STUB("IDirect3DVolumeTexture8::SetLOD"); return 0; }
static DWORD WINAPI vtex8_GetLOD(IDirect3DVolumeTexture8 *This) { D3DPT_STUB("IDirect3DVolumeTexture8::GetLOD"); return 0; }
static DWORD WINAPI vtex8_GetLevelCount(IDirect3DVolumeTexture8 *This) { D3DPT_STUB("IDirect3DVolumeTexture8::GetLevelCount"); return 0; }
static HRESULT WINAPI vtex8_GetLevelDesc(IDirect3DVolumeTexture8 *This, UINT Level,D3DVOLUME_DESC8 * pDesc) { D3DPT_STUB("IDirect3DVolumeTexture8::GetLevelDesc"); return E_NOTIMPL; }
static HRESULT WINAPI vtex8_GetVolumeLevel(IDirect3DVolumeTexture8 *This, UINT Level,IDirect3DVolume8 ** ppVolumeLevel) { D3DPT_STUB("IDirect3DVolumeTexture8::GetVolumeLevel"); return E_NOTIMPL; }
static HRESULT WINAPI vtex8_LockBox(IDirect3DVolumeTexture8 *This, UINT level, D3DLOCKED_BOX *locked_box, const D3DBOX *box, DWORD flags) { D3DPT_STUB("IDirect3DVolumeTexture8::LockBox"); return E_NOTIMPL; }
static HRESULT WINAPI vtex8_UnlockBox(IDirect3DVolumeTexture8 *This, UINT Level) { D3DPT_STUB("IDirect3DVolumeTexture8::UnlockBox"); return E_NOTIMPL; }
static HRESULT WINAPI vtex8_AddDirtyBox(IDirect3DVolumeTexture8 *This, const D3DBOX *dirty_box) { D3DPT_STUB("IDirect3DVolumeTexture8::AddDirtyBox"); return E_NOTIMPL; }
static const IDirect3DVolumeTexture8Vtbl vtex8_vtbl = {
    vtex8_QueryInterface,
    vtex8_AddRef,
    vtex8_Release,
    vtex8_GetDevice,
    vtex8_SetPrivateData,
    vtex8_GetPrivateData,
    vtex8_FreePrivateData,
    vtex8_SetPriority,
    vtex8_GetPriority,
    vtex8_PreLoad,
    vtex8_GetType,
    vtex8_SetLOD,
    vtex8_GetLOD,
    vtex8_GetLevelCount,
    vtex8_GetLevelDesc,
    vtex8_GetVolumeLevel,
    vtex8_LockBox,
    vtex8_UnlockBox,
    vtex8_AddDirtyBox,
};

typedef struct IDirect3DVolume8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DVolume8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DVolume8 *This);
    ULONG (WINAPI *Release)(IDirect3DVolume8 *This);
    HRESULT (WINAPI *GetDevice)(IDirect3DVolume8 *This, IDirect3DDevice8 ** ppDevice);
    HRESULT (WINAPI *SetPrivateData)(IDirect3DVolume8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
    HRESULT (WINAPI *GetPrivateData)(IDirect3DVolume8 *This, REFGUID refguid,void * pData, DWORD * pSizeOfData);
    HRESULT (WINAPI *FreePrivateData)(IDirect3DVolume8 *This, REFGUID refguid);
    HRESULT (WINAPI *GetContainer)(IDirect3DVolume8 *This, REFIID riid, void ** ppContainer);
    HRESULT (WINAPI *GetDesc)(IDirect3DVolume8 *This, D3DVOLUME_DESC8 * pDesc);
    HRESULT (WINAPI *LockBox)(IDirect3DVolume8 *This, D3DLOCKED_BOX *locked_box, const D3DBOX *box, DWORD flags);
    HRESULT (WINAPI *UnlockBox)(IDirect3DVolume8 *This);
} IDirect3DVolume8Vtbl;
struct IDirect3DVolume8 { const IDirect3DVolume8Vtbl *lpVtbl; };
/* --- IDirect3DVolume8: 11 methods --- */
static HRESULT WINAPI vol8_QueryInterface(IDirect3DVolume8 *This, REFIID riid, void** ppvObject) { D3DPT_STUB("IDirect3DVolume8::QueryInterface"); return E_NOTIMPL; }
static ULONG WINAPI vol8_AddRef(IDirect3DVolume8 *This) { D3DPT_STUB("IDirect3DVolume8::AddRef"); return 0; }
static ULONG WINAPI vol8_Release(IDirect3DVolume8 *This) { D3DPT_STUB("IDirect3DVolume8::Release"); return 0; }
static HRESULT WINAPI vol8_GetDevice(IDirect3DVolume8 *This, IDirect3DDevice8 ** ppDevice) { D3DPT_STUB("IDirect3DVolume8::GetDevice"); return E_NOTIMPL; }
static HRESULT WINAPI vol8_SetPrivateData(IDirect3DVolume8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags) { D3DPT_STUB("IDirect3DVolume8::SetPrivateData"); return E_NOTIMPL; }
static HRESULT WINAPI vol8_GetPrivateData(IDirect3DVolume8 *This, REFGUID refguid,void * pData, DWORD * pSizeOfData) { D3DPT_STUB("IDirect3DVolume8::GetPrivateData"); return E_NOTIMPL; }
static HRESULT WINAPI vol8_FreePrivateData(IDirect3DVolume8 *This, REFGUID refguid) { D3DPT_STUB("IDirect3DVolume8::FreePrivateData"); return E_NOTIMPL; }
static HRESULT WINAPI vol8_GetContainer(IDirect3DVolume8 *This, REFIID riid, void ** ppContainer) { D3DPT_STUB("IDirect3DVolume8::GetContainer"); return E_NOTIMPL; }
static HRESULT WINAPI vol8_GetDesc(IDirect3DVolume8 *This, D3DVOLUME_DESC8 * pDesc) { D3DPT_STUB("IDirect3DVolume8::GetDesc"); return E_NOTIMPL; }
static HRESULT WINAPI vol8_LockBox(IDirect3DVolume8 *This, D3DLOCKED_BOX *locked_box, const D3DBOX *box, DWORD flags) { D3DPT_STUB("IDirect3DVolume8::LockBox"); return E_NOTIMPL; }
static HRESULT WINAPI vol8_UnlockBox(IDirect3DVolume8 *This) { D3DPT_STUB("IDirect3DVolume8::UnlockBox"); return E_NOTIMPL; }
static const IDirect3DVolume8Vtbl vol8_vtbl = {
    vol8_QueryInterface,
    vol8_AddRef,
    vol8_Release,
    vol8_GetDevice,
    vol8_SetPrivateData,
    vol8_GetPrivateData,
    vol8_FreePrivateData,
    vol8_GetContainer,
    vol8_GetDesc,
    vol8_LockBox,
    vol8_UnlockBox,
};

typedef struct IDirect3DBaseTexture8Vtbl {
    HRESULT (WINAPI *QueryInterface)(IDirect3DBaseTexture8 *This, REFIID riid, void** ppvObject);
    ULONG (WINAPI *AddRef)(IDirect3DBaseTexture8 *This);
    ULONG (WINAPI *Release)(IDirect3DBaseTexture8 *This);
    HRESULT (WINAPI *GetDevice)(IDirect3DBaseTexture8 *This, IDirect3DDevice8 ** ppDevice);
    HRESULT (WINAPI *SetPrivateData)(IDirect3DBaseTexture8 *This, REFGUID refguid, const void *data, DWORD data_size, DWORD flags);
    HRESULT (WINAPI *GetPrivateData)(IDirect3DBaseTexture8 *This, REFGUID refguid, void * pData, DWORD * pSizeOfData);
    HRESULT (WINAPI *FreePrivateData)(IDirect3DBaseTexture8 *This, REFGUID refguid);
    DWORD (WINAPI *SetPriority)(IDirect3DBaseTexture8 *This, DWORD PriorityNew);
    DWORD (WINAPI *GetPriority)(IDirect3DBaseTexture8 *This);
    void (WINAPI *PreLoad)(IDirect3DBaseTexture8 *This);
    D3DRESOURCETYPE (WINAPI *GetType)(IDirect3DBaseTexture8 *This);
    DWORD (WINAPI *SetLOD)(IDirect3DBaseTexture8 *This, DWORD LODNew);
    DWORD (WINAPI *GetLOD)(IDirect3DBaseTexture8 *This);
    DWORD (WINAPI *GetLevelCount)(IDirect3DBaseTexture8 *This);
} IDirect3DBaseTexture8Vtbl;
struct IDirect3DBaseTexture8 { const IDirect3DBaseTexture8Vtbl *lpVtbl; };
#endif
