/* generated by gen_vtbl.py from mingw d3d9.h; do not edit */
#ifndef D3D9_VTBL_H
#define D3D9_VTBL_H
/* --- IDirect3D9: 17 methods --- */
HRESULT WINAPI d3d_QueryInterface(IDirect3D9 *This, REFIID riid, void** ppvObject);
ULONG WINAPI d3d_AddRef(IDirect3D9 *This);
ULONG WINAPI d3d_Release(IDirect3D9 *This);
HRESULT WINAPI d3d_RegisterSoftwareDevice(IDirect3D9 *This, void* pInitializeFunction);
UINT WINAPI d3d_GetAdapterCount(IDirect3D9 *This);
HRESULT WINAPI d3d_GetAdapterIdentifier(IDirect3D9 *This, UINT Adapter, DWORD Flags, D3DADAPTER_IDENTIFIER9* pIdentifier);
UINT WINAPI d3d_GetAdapterModeCount(IDirect3D9 *This, UINT Adapter, D3DFORMAT Format);
HRESULT WINAPI d3d_EnumAdapterModes(IDirect3D9 *This, UINT Adapter, D3DFORMAT Format, UINT Mode, D3DDISPLAYMODE* pMode);
HRESULT WINAPI d3d_GetAdapterDisplayMode(IDirect3D9 *This, UINT Adapter, D3DDISPLAYMODE* pMode);
HRESULT WINAPI d3d_CheckDeviceType(IDirect3D9 *This, UINT iAdapter, D3DDEVTYPE DevType, D3DFORMAT DisplayFormat, D3DFORMAT BackBufferFormat, WINBOOL bWindowed);
HRESULT WINAPI d3d_CheckDeviceFormat(IDirect3D9 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, DWORD Usage, D3DRESOURCETYPE RType, D3DFORMAT CheckFormat);
HRESULT WINAPI d3d_CheckDeviceMultiSampleType(IDirect3D9 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SurfaceFormat, WINBOOL Windowed, D3DMULTISAMPLE_TYPE MultiSampleType, DWORD* pQualityLevels);
HRESULT WINAPI d3d_CheckDepthStencilMatch(IDirect3D9 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT AdapterFormat, D3DFORMAT RenderTargetFormat, D3DFORMAT DepthStencilFormat);
HRESULT WINAPI d3d_CheckDeviceFormatConversion(IDirect3D9 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DFORMAT SourceFormat, D3DFORMAT TargetFormat);
HRESULT WINAPI d3d_GetDeviceCaps(IDirect3D9 *This, UINT Adapter, D3DDEVTYPE DeviceType, D3DCAPS9* pCaps);
HMONITOR WINAPI d3d_GetAdapterMonitor(IDirect3D9 *This, UINT Adapter);
HRESULT WINAPI d3d_CreateDevice(IDirect3D9 *This, UINT Adapter, D3DDEVTYPE DeviceType, HWND hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS* pPresentationParameters, struct IDirect3DDevice9** ppReturnedDeviceInterface);
static const IDirect3D9Vtbl d3d_vtbl = {
    d3d_QueryInterface,
    d3d_AddRef,
    d3d_Release,
    d3d_RegisterSoftwareDevice,
    d3d_GetAdapterCount,
    d3d_GetAdapterIdentifier,
    d3d_GetAdapterModeCount,
    d3d_EnumAdapterModes,
    d3d_GetAdapterDisplayMode,
    d3d_CheckDeviceType,
    d3d_CheckDeviceFormat,
    d3d_CheckDeviceMultiSampleType,
    d3d_CheckDepthStencilMatch,
    d3d_CheckDeviceFormatConversion,
    d3d_GetDeviceCaps,
    d3d_GetAdapterMonitor,
    d3d_CreateDevice,
};

/* --- IDirect3DDevice9: 119 methods --- */
HRESULT WINAPI dev_QueryInterface(IDirect3DDevice9 *This, REFIID riid, void** ppvObject);
ULONG WINAPI dev_AddRef(IDirect3DDevice9 *This);
ULONG WINAPI dev_Release(IDirect3DDevice9 *This);
HRESULT WINAPI dev_TestCooperativeLevel(IDirect3DDevice9 *This);
UINT WINAPI dev_GetAvailableTextureMem(IDirect3DDevice9 *This);
HRESULT WINAPI dev_EvictManagedResources(IDirect3DDevice9 *This);
HRESULT WINAPI dev_GetDirect3D(IDirect3DDevice9 *This, IDirect3D9** ppD3D9);
HRESULT WINAPI dev_GetDeviceCaps(IDirect3DDevice9 *This, D3DCAPS9* pCaps);
HRESULT WINAPI dev_GetDisplayMode(IDirect3DDevice9 *This, UINT iSwapChain, D3DDISPLAYMODE* pMode);
HRESULT WINAPI dev_GetCreationParameters(IDirect3DDevice9 *This, D3DDEVICE_CREATION_PARAMETERS *pParameters);
HRESULT WINAPI dev_SetCursorProperties(IDirect3DDevice9 *This, UINT XHotSpot, UINT YHotSpot, IDirect3DSurface9* pCursorBitmap);
void WINAPI dev_SetCursorPosition(IDirect3DDevice9 *This, int X,int Y, DWORD Flags);
WINBOOL WINAPI dev_ShowCursor(IDirect3DDevice9 *This, WINBOOL bShow);
static HRESULT WINAPI dev_CreateAdditionalSwapChain(IDirect3DDevice9 *This, D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DSwapChain9** pSwapChain) { D3DPT_STUB("IDirect3DDevice9::CreateAdditionalSwapChain"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetSwapChain(IDirect3DDevice9 *This, UINT iSwapChain, IDirect3DSwapChain9** pSwapChain) { D3DPT_STUB("IDirect3DDevice9::GetSwapChain"); return E_NOTIMPL; }
UINT WINAPI dev_GetNumberOfSwapChains(IDirect3DDevice9 *This);
HRESULT WINAPI dev_Reset(IDirect3DDevice9 *This, D3DPRESENT_PARAMETERS* pPresentationParameters);
HRESULT WINAPI dev_Present(IDirect3DDevice9 *This, const RECT *src_rect, const RECT *dst_rect, HWND dst_window_override, const RGNDATA *dirty_region);
static HRESULT WINAPI dev_GetBackBuffer(IDirect3DDevice9 *This, UINT iSwapChain, UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9** ppBackBuffer) { D3DPT_STUB("IDirect3DDevice9::GetBackBuffer"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetRasterStatus(IDirect3DDevice9 *This, UINT iSwapChain, D3DRASTER_STATUS* pRasterStatus) { D3DPT_STUB("IDirect3DDevice9::GetRasterStatus"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetDialogBoxMode(IDirect3DDevice9 *This, WINBOOL bEnableDialogs) { D3DPT_STUB("IDirect3DDevice9::SetDialogBoxMode"); return E_NOTIMPL; }
static void WINAPI dev_SetGammaRamp(IDirect3DDevice9 *This, UINT swapchain_idx, DWORD flags, const D3DGAMMARAMP *ramp) { D3DPT_STUB("IDirect3DDevice9::SetGammaRamp");  }
static void WINAPI dev_GetGammaRamp(IDirect3DDevice9 *This, UINT iSwapChain, D3DGAMMARAMP* pRamp) { D3DPT_STUB("IDirect3DDevice9::GetGammaRamp");  }
static HRESULT WINAPI dev_CreateTexture(IDirect3DDevice9 *This, UINT Width, UINT Height, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DTexture9** ppTexture, HANDLE* pSharedHandle) { D3DPT_STUB("IDirect3DDevice9::CreateTexture"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateVolumeTexture(IDirect3DDevice9 *This, UINT Width, UINT Height, UINT Depth, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DVolumeTexture9** ppVolumeTexture, HANDLE* pSharedHandle) { D3DPT_STUB("IDirect3DDevice9::CreateVolumeTexture"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateCubeTexture(IDirect3DDevice9 *This, UINT EdgeLength, UINT Levels, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DCubeTexture9** ppCubeTexture, HANDLE* pSharedHandle) { D3DPT_STUB("IDirect3DDevice9::CreateCubeTexture"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateVertexBuffer(IDirect3DDevice9 *This, UINT Length, DWORD Usage, DWORD FVF, D3DPOOL Pool, IDirect3DVertexBuffer9** ppVertexBuffer, HANDLE* pSharedHandle) { D3DPT_STUB("IDirect3DDevice9::CreateVertexBuffer"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateIndexBuffer(IDirect3DDevice9 *This, UINT Length, DWORD Usage, D3DFORMAT Format, D3DPOOL Pool, IDirect3DIndexBuffer9** ppIndexBuffer, HANDLE* pSharedHandle) { D3DPT_STUB("IDirect3DDevice9::CreateIndexBuffer"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateRenderTarget(IDirect3DDevice9 *This, UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, WINBOOL Lockable, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) { D3DPT_STUB("IDirect3DDevice9::CreateRenderTarget"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateDepthStencilSurface(IDirect3DDevice9 *This, UINT Width, UINT Height, D3DFORMAT Format, D3DMULTISAMPLE_TYPE MultiSample, DWORD MultisampleQuality, WINBOOL Discard, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) { D3DPT_STUB("IDirect3DDevice9::CreateDepthStencilSurface"); return E_NOTIMPL; }
static HRESULT WINAPI dev_UpdateSurface(IDirect3DDevice9 *This, IDirect3DSurface9 *src_surface, const RECT *src_rect, IDirect3DSurface9 *dst_surface, const POINT *dst_point) { D3DPT_STUB("IDirect3DDevice9::UpdateSurface"); return E_NOTIMPL; }
static HRESULT WINAPI dev_UpdateTexture(IDirect3DDevice9 *This, IDirect3DBaseTexture9* pSourceTexture, IDirect3DBaseTexture9* pDestinationTexture) { D3DPT_STUB("IDirect3DDevice9::UpdateTexture"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetRenderTargetData(IDirect3DDevice9 *This, IDirect3DSurface9* pRenderTarget, IDirect3DSurface9* pDestSurface) { D3DPT_STUB("IDirect3DDevice9::GetRenderTargetData"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetFrontBufferData(IDirect3DDevice9 *This, UINT iSwapChain, IDirect3DSurface9* pDestSurface) { D3DPT_STUB("IDirect3DDevice9::GetFrontBufferData"); return E_NOTIMPL; }
static HRESULT WINAPI dev_StretchRect(IDirect3DDevice9 *This, IDirect3DSurface9 *src_surface, const RECT *src_rect, IDirect3DSurface9 *dst_surface, const RECT *dst_rect, D3DTEXTUREFILTERTYPE filter) { D3DPT_STUB("IDirect3DDevice9::StretchRect"); return E_NOTIMPL; }
static HRESULT WINAPI dev_ColorFill(IDirect3DDevice9 *This, IDirect3DSurface9 *surface, const RECT *rect, D3DCOLOR color) { D3DPT_STUB("IDirect3DDevice9::ColorFill"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateOffscreenPlainSurface(IDirect3DDevice9 *This, UINT Width, UINT Height, D3DFORMAT Format, D3DPOOL Pool, IDirect3DSurface9** ppSurface, HANDLE* pSharedHandle) { D3DPT_STUB("IDirect3DDevice9::CreateOffscreenPlainSurface"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetRenderTarget(IDirect3DDevice9 *This, DWORD RenderTargetIndex, IDirect3DSurface9* pRenderTarget) { D3DPT_STUB("IDirect3DDevice9::SetRenderTarget"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetRenderTarget(IDirect3DDevice9 *This, DWORD RenderTargetIndex, IDirect3DSurface9** ppRenderTarget) { D3DPT_STUB("IDirect3DDevice9::GetRenderTarget"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetDepthStencilSurface(IDirect3DDevice9 *This, IDirect3DSurface9* pNewZStencil) { D3DPT_STUB("IDirect3DDevice9::SetDepthStencilSurface"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetDepthStencilSurface(IDirect3DDevice9 *This, IDirect3DSurface9** ppZStencilSurface) { D3DPT_STUB("IDirect3DDevice9::GetDepthStencilSurface"); return E_NOTIMPL; }
HRESULT WINAPI dev_BeginScene(IDirect3DDevice9 *This);
HRESULT WINAPI dev_EndScene(IDirect3DDevice9 *This);
HRESULT WINAPI dev_Clear(IDirect3DDevice9 *This, DWORD rect_count, const D3DRECT *rects, DWORD flags, D3DCOLOR color, float z, DWORD stencil);
HRESULT WINAPI dev_SetTransform(IDirect3DDevice9 *This, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix);
HRESULT WINAPI dev_GetTransform(IDirect3DDevice9 *This, D3DTRANSFORMSTATETYPE State, D3DMATRIX* pMatrix);
HRESULT WINAPI dev_MultiplyTransform(IDirect3DDevice9 *This, D3DTRANSFORMSTATETYPE state, const D3DMATRIX *matrix);
HRESULT WINAPI dev_SetViewport(IDirect3DDevice9 *This, const D3DVIEWPORT9 *viewport);
HRESULT WINAPI dev_GetViewport(IDirect3DDevice9 *This, D3DVIEWPORT9* pViewport);
HRESULT WINAPI dev_SetMaterial(IDirect3DDevice9 *This, const D3DMATERIAL9 *material);
HRESULT WINAPI dev_GetMaterial(IDirect3DDevice9 *This, D3DMATERIAL9* pMaterial);
HRESULT WINAPI dev_SetLight(IDirect3DDevice9 *This, DWORD index, const D3DLIGHT9 *light);
HRESULT WINAPI dev_GetLight(IDirect3DDevice9 *This, DWORD Index, D3DLIGHT9*);
HRESULT WINAPI dev_LightEnable(IDirect3DDevice9 *This, DWORD Index, WINBOOL Enable);
HRESULT WINAPI dev_GetLightEnable(IDirect3DDevice9 *This, DWORD Index, WINBOOL* pEnable);
static HRESULT WINAPI dev_SetClipPlane(IDirect3DDevice9 *This, DWORD index, const float *plane) { D3DPT_STUB("IDirect3DDevice9::SetClipPlane"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetClipPlane(IDirect3DDevice9 *This, DWORD Index, float* pPlane) { D3DPT_STUB("IDirect3DDevice9::GetClipPlane"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetRenderState(IDirect3DDevice9 *This, D3DRENDERSTATETYPE State, DWORD Value);
HRESULT WINAPI dev_GetRenderState(IDirect3DDevice9 *This, D3DRENDERSTATETYPE State, DWORD* pValue);
static HRESULT WINAPI dev_CreateStateBlock(IDirect3DDevice9 *This, D3DSTATEBLOCKTYPE Type, IDirect3DStateBlock9** ppSB) { D3DPT_STUB("IDirect3DDevice9::CreateStateBlock"); return E_NOTIMPL; }
static HRESULT WINAPI dev_BeginStateBlock(IDirect3DDevice9 *This) { D3DPT_STUB("IDirect3DDevice9::BeginStateBlock"); return E_NOTIMPL; }
static HRESULT WINAPI dev_EndStateBlock(IDirect3DDevice9 *This, IDirect3DStateBlock9** ppSB) { D3DPT_STUB("IDirect3DDevice9::EndStateBlock"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetClipStatus(IDirect3DDevice9 *This, const D3DCLIPSTATUS9 *clip_status) { D3DPT_STUB("IDirect3DDevice9::SetClipStatus"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetClipStatus(IDirect3DDevice9 *This, D3DCLIPSTATUS9* pClipStatus) { D3DPT_STUB("IDirect3DDevice9::GetClipStatus"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetTexture(IDirect3DDevice9 *This, DWORD Stage, IDirect3DBaseTexture9** ppTexture) { D3DPT_STUB("IDirect3DDevice9::GetTexture"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetTexture(IDirect3DDevice9 *This, DWORD Stage, IDirect3DBaseTexture9* pTexture);
HRESULT WINAPI dev_GetTextureStageState(IDirect3DDevice9 *This, DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD* pValue);
HRESULT WINAPI dev_SetTextureStageState(IDirect3DDevice9 *This, DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD Value);
HRESULT WINAPI dev_GetSamplerState(IDirect3DDevice9 *This, DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD* pValue);
HRESULT WINAPI dev_SetSamplerState(IDirect3DDevice9 *This, DWORD Sampler, D3DSAMPLERSTATETYPE Type, DWORD Value);
HRESULT WINAPI dev_ValidateDevice(IDirect3DDevice9 *This, DWORD* pNumPasses);
static HRESULT WINAPI dev_SetPaletteEntries(IDirect3DDevice9 *This, UINT palette_idx, const PALETTEENTRY *entries) { D3DPT_STUB("IDirect3DDevice9::SetPaletteEntries"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetPaletteEntries(IDirect3DDevice9 *This, UINT PaletteNumber,PALETTEENTRY* pEntries) { D3DPT_STUB("IDirect3DDevice9::GetPaletteEntries"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetCurrentTexturePalette(IDirect3DDevice9 *This, UINT PaletteNumber) { D3DPT_STUB("IDirect3DDevice9::SetCurrentTexturePalette"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetCurrentTexturePalette(IDirect3DDevice9 *This, UINT *PaletteNumber) { D3DPT_STUB("IDirect3DDevice9::GetCurrentTexturePalette"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetScissorRect(IDirect3DDevice9 *This, const RECT *rect);
HRESULT WINAPI dev_GetScissorRect(IDirect3DDevice9 *This, RECT* pRect);
HRESULT WINAPI dev_SetSoftwareVertexProcessing(IDirect3DDevice9 *This, WINBOOL bSoftware);
WINBOOL WINAPI dev_GetSoftwareVertexProcessing(IDirect3DDevice9 *This);
static HRESULT WINAPI dev_SetNPatchMode(IDirect3DDevice9 *This, float nSegments) { D3DPT_STUB("IDirect3DDevice9::SetNPatchMode"); return E_NOTIMPL; }
static float WINAPI dev_GetNPatchMode(IDirect3DDevice9 *This) { D3DPT_STUB("IDirect3DDevice9::GetNPatchMode"); return 0; }
static HRESULT WINAPI dev_DrawPrimitive(IDirect3DDevice9 *This, D3DPRIMITIVETYPE PrimitiveType, UINT StartVertex, UINT PrimitiveCount) { D3DPT_STUB("IDirect3DDevice9::DrawPrimitive"); return E_NOTIMPL; }
static HRESULT WINAPI dev_DrawIndexedPrimitive(IDirect3DDevice9 *This, D3DPRIMITIVETYPE, INT BaseVertexIndex, UINT MinVertexIndex, UINT NumVertices, UINT startIndex, UINT primCount) { D3DPT_STUB("IDirect3DDevice9::DrawIndexedPrimitive"); return E_NOTIMPL; }
HRESULT WINAPI dev_DrawPrimitiveUP(IDirect3DDevice9 *This, D3DPRIMITIVETYPE primitive_type, UINT primitive_count, const void *data, UINT stride);
static HRESULT WINAPI dev_DrawIndexedPrimitiveUP(IDirect3DDevice9 *This, D3DPRIMITIVETYPE primitive_type, UINT min_vertex_idx, UINT vertex_count, UINT primitive_count, const void *index_data, D3DFORMAT index_format, const void *data, UINT stride) { D3DPT_STUB("IDirect3DDevice9::DrawIndexedPrimitiveUP"); return E_NOTIMPL; }
static HRESULT WINAPI dev_ProcessVertices(IDirect3DDevice9 *This, UINT SrcStartIndex, UINT DestIndex, UINT VertexCount, IDirect3DVertexBuffer9* pDestBuffer, IDirect3DVertexDeclaration9* pVertexDecl, DWORD Flags) { D3DPT_STUB("IDirect3DDevice9::ProcessVertices"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateVertexDeclaration(IDirect3DDevice9 *This, const D3DVERTEXELEMENT9 *elements, IDirect3DVertexDeclaration9 **declaration) { D3DPT_STUB("IDirect3DDevice9::CreateVertexDeclaration"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetVertexDeclaration(IDirect3DDevice9 *This, IDirect3DVertexDeclaration9* pDecl) { D3DPT_STUB("IDirect3DDevice9::SetVertexDeclaration"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetVertexDeclaration(IDirect3DDevice9 *This, IDirect3DVertexDeclaration9** ppDecl) { D3DPT_STUB("IDirect3DDevice9::GetVertexDeclaration"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetFVF(IDirect3DDevice9 *This, DWORD FVF);
HRESULT WINAPI dev_GetFVF(IDirect3DDevice9 *This, DWORD* pFVF);
static HRESULT WINAPI dev_CreateVertexShader(IDirect3DDevice9 *This, const DWORD *byte_code, IDirect3DVertexShader9 **shader) { D3DPT_STUB("IDirect3DDevice9::CreateVertexShader"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetVertexShader(IDirect3DDevice9 *This, IDirect3DVertexShader9* pShader);
static HRESULT WINAPI dev_GetVertexShader(IDirect3DDevice9 *This, IDirect3DVertexShader9** ppShader) { D3DPT_STUB("IDirect3DDevice9::GetVertexShader"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetVertexShaderConstantF(IDirect3DDevice9 *This, UINT reg_idx, const float *data, UINT count);
static HRESULT WINAPI dev_GetVertexShaderConstantF(IDirect3DDevice9 *This, UINT StartRegister, float* pConstantData, UINT Vector4fCount) { D3DPT_STUB("IDirect3DDevice9::GetVertexShaderConstantF"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetVertexShaderConstantI(IDirect3DDevice9 *This, UINT reg_idx, const int *data, UINT count) { D3DPT_STUB("IDirect3DDevice9::SetVertexShaderConstantI"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetVertexShaderConstantI(IDirect3DDevice9 *This, UINT StartRegister, int* pConstantData, UINT Vector4iCount) { D3DPT_STUB("IDirect3DDevice9::GetVertexShaderConstantI"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetVertexShaderConstantB(IDirect3DDevice9 *This, UINT reg_idx, const WINBOOL *data, UINT count) { D3DPT_STUB("IDirect3DDevice9::SetVertexShaderConstantB"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetVertexShaderConstantB(IDirect3DDevice9 *This, UINT StartRegister, WINBOOL* pConstantData, UINT BoolCount) { D3DPT_STUB("IDirect3DDevice9::GetVertexShaderConstantB"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetStreamSource(IDirect3DDevice9 *This, UINT StreamNumber, IDirect3DVertexBuffer9* pStreamData, UINT OffsetInBytes, UINT Stride);
static HRESULT WINAPI dev_GetStreamSource(IDirect3DDevice9 *This, UINT StreamNumber, IDirect3DVertexBuffer9** ppStreamData, UINT* OffsetInBytes, UINT* pStride) { D3DPT_STUB("IDirect3DDevice9::GetStreamSource"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetStreamSourceFreq(IDirect3DDevice9 *This, UINT StreamNumber, UINT Divider) { D3DPT_STUB("IDirect3DDevice9::SetStreamSourceFreq"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetStreamSourceFreq(IDirect3DDevice9 *This, UINT StreamNumber, UINT* Divider) { D3DPT_STUB("IDirect3DDevice9::GetStreamSourceFreq"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetIndices(IDirect3DDevice9 *This, IDirect3DIndexBuffer9* pIndexData);
static HRESULT WINAPI dev_GetIndices(IDirect3DDevice9 *This, IDirect3DIndexBuffer9** ppIndexData) { D3DPT_STUB("IDirect3DDevice9::GetIndices"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreatePixelShader(IDirect3DDevice9 *This, const DWORD *byte_code, IDirect3DPixelShader9 **shader) { D3DPT_STUB("IDirect3DDevice9::CreatePixelShader"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetPixelShader(IDirect3DDevice9 *This, IDirect3DPixelShader9* pShader);
static HRESULT WINAPI dev_GetPixelShader(IDirect3DDevice9 *This, IDirect3DPixelShader9** ppShader) { D3DPT_STUB("IDirect3DDevice9::GetPixelShader"); return E_NOTIMPL; }
HRESULT WINAPI dev_SetPixelShaderConstantF(IDirect3DDevice9 *This, UINT reg_idx, const float *data, UINT count);
static HRESULT WINAPI dev_GetPixelShaderConstantF(IDirect3DDevice9 *This, UINT StartRegister, float* pConstantData, UINT Vector4fCount) { D3DPT_STUB("IDirect3DDevice9::GetPixelShaderConstantF"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetPixelShaderConstantI(IDirect3DDevice9 *This, UINT reg_idx, const int *data, UINT count) { D3DPT_STUB("IDirect3DDevice9::SetPixelShaderConstantI"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetPixelShaderConstantI(IDirect3DDevice9 *This, UINT StartRegister, int* pConstantData, UINT Vector4iCount) { D3DPT_STUB("IDirect3DDevice9::GetPixelShaderConstantI"); return E_NOTIMPL; }
static HRESULT WINAPI dev_SetPixelShaderConstantB(IDirect3DDevice9 *This, UINT reg_idx, const WINBOOL *data, UINT count) { D3DPT_STUB("IDirect3DDevice9::SetPixelShaderConstantB"); return E_NOTIMPL; }
static HRESULT WINAPI dev_GetPixelShaderConstantB(IDirect3DDevice9 *This, UINT StartRegister, WINBOOL* pConstantData, UINT BoolCount) { D3DPT_STUB("IDirect3DDevice9::GetPixelShaderConstantB"); return E_NOTIMPL; }
static HRESULT WINAPI dev_DrawRectPatch(IDirect3DDevice9 *This, UINT handle, const float *segment_count, const D3DRECTPATCH_INFO *patch_info) { D3DPT_STUB("IDirect3DDevice9::DrawRectPatch"); return E_NOTIMPL; }
static HRESULT WINAPI dev_DrawTriPatch(IDirect3DDevice9 *This, UINT handle, const float *segment_count, const D3DTRIPATCH_INFO *patch_info) { D3DPT_STUB("IDirect3DDevice9::DrawTriPatch"); return E_NOTIMPL; }
static HRESULT WINAPI dev_DeletePatch(IDirect3DDevice9 *This, UINT Handle) { D3DPT_STUB("IDirect3DDevice9::DeletePatch"); return E_NOTIMPL; }
static HRESULT WINAPI dev_CreateQuery(IDirect3DDevice9 *This, D3DQUERYTYPE Type, IDirect3DQuery9** ppQuery) { D3DPT_STUB("IDirect3DDevice9::CreateQuery"); return E_NOTIMPL; }
static const IDirect3DDevice9Vtbl dev_vtbl = {
    dev_QueryInterface,
    dev_AddRef,
    dev_Release,
    dev_TestCooperativeLevel,
    dev_GetAvailableTextureMem,
    dev_EvictManagedResources,
    dev_GetDirect3D,
    dev_GetDeviceCaps,
    dev_GetDisplayMode,
    dev_GetCreationParameters,
    dev_SetCursorProperties,
    dev_SetCursorPosition,
    dev_ShowCursor,
    dev_CreateAdditionalSwapChain,
    dev_GetSwapChain,
    dev_GetNumberOfSwapChains,
    dev_Reset,
    dev_Present,
    dev_GetBackBuffer,
    dev_GetRasterStatus,
    dev_SetDialogBoxMode,
    dev_SetGammaRamp,
    dev_GetGammaRamp,
    dev_CreateTexture,
    dev_CreateVolumeTexture,
    dev_CreateCubeTexture,
    dev_CreateVertexBuffer,
    dev_CreateIndexBuffer,
    dev_CreateRenderTarget,
    dev_CreateDepthStencilSurface,
    dev_UpdateSurface,
    dev_UpdateTexture,
    dev_GetRenderTargetData,
    dev_GetFrontBufferData,
    dev_StretchRect,
    dev_ColorFill,
    dev_CreateOffscreenPlainSurface,
    dev_SetRenderTarget,
    dev_GetRenderTarget,
    dev_SetDepthStencilSurface,
    dev_GetDepthStencilSurface,
    dev_BeginScene,
    dev_EndScene,
    dev_Clear,
    dev_SetTransform,
    dev_GetTransform,
    dev_MultiplyTransform,
    dev_SetViewport,
    dev_GetViewport,
    dev_SetMaterial,
    dev_GetMaterial,
    dev_SetLight,
    dev_GetLight,
    dev_LightEnable,
    dev_GetLightEnable,
    dev_SetClipPlane,
    dev_GetClipPlane,
    dev_SetRenderState,
    dev_GetRenderState,
    dev_CreateStateBlock,
    dev_BeginStateBlock,
    dev_EndStateBlock,
    dev_SetClipStatus,
    dev_GetClipStatus,
    dev_GetTexture,
    dev_SetTexture,
    dev_GetTextureStageState,
    dev_SetTextureStageState,
    dev_GetSamplerState,
    dev_SetSamplerState,
    dev_ValidateDevice,
    dev_SetPaletteEntries,
    dev_GetPaletteEntries,
    dev_SetCurrentTexturePalette,
    dev_GetCurrentTexturePalette,
    dev_SetScissorRect,
    dev_GetScissorRect,
    dev_SetSoftwareVertexProcessing,
    dev_GetSoftwareVertexProcessing,
    dev_SetNPatchMode,
    dev_GetNPatchMode,
    dev_DrawPrimitive,
    dev_DrawIndexedPrimitive,
    dev_DrawPrimitiveUP,
    dev_DrawIndexedPrimitiveUP,
    dev_ProcessVertices,
    dev_CreateVertexDeclaration,
    dev_SetVertexDeclaration,
    dev_GetVertexDeclaration,
    dev_SetFVF,
    dev_GetFVF,
    dev_CreateVertexShader,
    dev_SetVertexShader,
    dev_GetVertexShader,
    dev_SetVertexShaderConstantF,
    dev_GetVertexShaderConstantF,
    dev_SetVertexShaderConstantI,
    dev_GetVertexShaderConstantI,
    dev_SetVertexShaderConstantB,
    dev_GetVertexShaderConstantB,
    dev_SetStreamSource,
    dev_GetStreamSource,
    dev_SetStreamSourceFreq,
    dev_GetStreamSourceFreq,
    dev_SetIndices,
    dev_GetIndices,
    dev_CreatePixelShader,
    dev_SetPixelShader,
    dev_GetPixelShader,
    dev_SetPixelShaderConstantF,
    dev_GetPixelShaderConstantF,
    dev_SetPixelShaderConstantI,
    dev_GetPixelShaderConstantI,
    dev_SetPixelShaderConstantB,
    dev_GetPixelShaderConstantB,
    dev_DrawRectPatch,
    dev_DrawTriPatch,
    dev_DeletePatch,
    dev_CreateQuery,
};

#endif
