#!/usr/bin/env python3
"""Generate d3d9_vtbl.h for the paravirtual d3d9.dll from mingw's d3d9.h:
prototypes for every IDirect3D9 / IDirect3DDevice9 method (so the
implementations are signature-checked), E_NOTIMPL stubs (log once) for
the ones not implemented, and the two vtables in header order.
Usage: gen_vtbl.py /usr/i686-w64-mingw32/include/d3d9.h > d3d9_vtbl.h
Implemented method names are read from the D3DPT_IMPL_* lists below."""
import re, sys

IMPL_D3D = set("""QueryInterface AddRef Release RegisterSoftwareDevice GetAdapterCount
GetAdapterIdentifier GetAdapterModeCount EnumAdapterModes GetAdapterDisplayMode CheckDeviceType
CheckDeviceFormat CheckDeviceMultiSampleType CheckDepthStencilMatch CheckDeviceFormatConversion
GetDeviceCaps GetAdapterMonitor CreateDevice""".split())
IMPL_RES = set("""QueryInterface AddRef Release GetDevice SetPrivateData GetPrivateData FreePrivateData
SetPriority GetPriority PreLoad GetType""".split())
IMPL_VB = IMPL_RES | set("Lock Unlock GetDesc".split())
IMPL_IB = IMPL_VB
IMPL_TEX = IMPL_RES | set("""SetLOD GetLOD GetLevelCount SetAutoGenFilterType GetAutoGenFilterType
GenerateMipSubLevels GetLevelDesc GetSurfaceLevel LockRect UnlockRect AddDirtyRect""".split())
IMPL_SURF = IMPL_RES | set("GetContainer GetDesc LockRect UnlockRect".split())
IMPL_SH = set("QueryInterface AddRef Release GetDevice GetFunction".split())
IMPL_DEV = set("""QueryInterface AddRef Release TestCooperativeLevel GetAvailableTextureMem
EvictManagedResources GetDirect3D GetDeviceCaps GetDisplayMode GetCreationParameters
SetCursorProperties SetCursorPosition ShowCursor GetNumberOfSwapChains Reset Present
BeginScene EndScene Clear SetTransform GetTransform MultiplyTransform SetViewport GetViewport
SetMaterial GetMaterial SetLight GetLight LightEnable GetLightEnable SetRenderState GetRenderState
SetTexture SetTextureStageState GetTextureStageState SetSamplerState GetSamplerState ValidateDevice
SetScissorRect GetScissorRect SetSoftwareVertexProcessing GetSoftwareVertexProcessing
DrawPrimitiveUP SetFVF GetFVF SetVertexShader SetPixelShader SetStreamSource SetIndices
SetVertexShaderConstantF SetPixelShaderConstantF GetVertexShader GetPixelShader GetStreamSource GetIndices
GetTexture CreateTexture CreateVertexBuffer CreateIndexBuffer CreateRenderTarget CreateDepthStencilSurface
CreateOffscreenPlainSurface GetRenderTargetData StretchRect SetRenderTarget GetRenderTarget
SetDepthStencilSurface GetDepthStencilSurface GetBackBuffer DrawPrimitive DrawIndexedPrimitive
DrawIndexedPrimitiveUP CreateVertexShader CreatePixelShader GetSwapChain SetClipPlane GetClipPlane""".split())

src = open(sys.argv[1]).read()
rx = re.compile(r'STDMETHOD(?:_\(\s*([^,]+?)\s*,\s*(\w+)\s*\)|\((\w+)\))\s*\(\s*THIS(?:_\s*(.*?))?\s*\)\s*PURE;', re.S)

def methods(iface):
    m = re.search(r'DECLARE_INTERFACE_IID_\(%s,.*?\n\{(.*?)\n\};' % iface, src, re.S)
    out = []
    for r in rx.finditer(m.group(1)):
        ret = (r.group(1) or 'HRESULT').strip()
        name = r.group(2) or r.group(3)
        args = ' '.join((r.group(4) or '').split())
        out.append((ret, name, args))
    expect = {'IDirect3D9': 17, 'IDirect3DDevice9': 119, 'IDirect3DVertexBuffer9': 14, 'IDirect3DIndexBuffer9': 14,
              'IDirect3DTexture9': 22, 'IDirect3DSurface9': 17, 'IDirect3DVertexShader9': 5, 'IDirect3DPixelShader9': 5}[iface]
    assert len(out) == expect, (iface, len(out))
    return out

def emit(iface, prefix, impl):
    ms = methods(iface)
    print('/* --- %s: %d methods --- */' % (iface, len(ms)))
    for ret, name, args in ms:
        proto = '%s WINAPI %s_%s(%s *This%s)' % (ret, prefix, name, iface, (', ' + args) if args else '')
        if name in impl:
            print('%s;' % proto)
        else:
            if ret == 'HRESULT': rv = 'E_NOTIMPL'
            elif ret == 'void': rv = None
            else: rv = '0'
            print('static %s { D3DPT_STUB("%s::%s"); %s }' % (proto, iface, name, ('return %s;' % rv) if rv else ''))
    print('static const %sVtbl %s_vtbl = {' % (iface, prefix))
    for ret, name, args in ms:
        print('    %s_%s,' % (prefix, name))
    print('};')
    print()

print('/* generated by gen_vtbl.py from mingw d3d9.h; do not edit */')
print('#ifndef D3D9_VTBL_H\n#define D3D9_VTBL_H')
emit('IDirect3D9', 'd3d', IMPL_D3D)
emit('IDirect3DDevice9', 'dev', IMPL_DEV)
emit('IDirect3DVertexBuffer9', 'vb', IMPL_VB)
emit('IDirect3DIndexBuffer9', 'ib', IMPL_IB)
emit('IDirect3DTexture9', 'tex', IMPL_TEX)
emit('IDirect3DSurface9', 'surf', IMPL_SURF)
emit('IDirect3DVertexShader9', 'vs', IMPL_SH)
emit('IDirect3DPixelShader9', 'ps', IMPL_SH)
print('#endif')
